In [232]:
import xgboost as xgb
from sklearn.ensemble import RandomForestRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import log_loss
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.model_selection import train_test_split

In [233]:
#Limpieza del dataset como en TP1

oportunidades = pd.read_csv("Train_TP2_Datos_2020-2C.csv")
oportunidades['Account_Created_Date'] = pd.to_datetime(oportunidades['Account_Created_Date'])
oportunidades['Opportunity_Created_Date'] = pd.to_datetime(oportunidades['Opportunity_Created_Date'])
oportunidades['Quote_Expiry_Date'] = pd.to_datetime(oportunidades['Quote_Expiry_Date'])
oportunidades['Last_Modified_Date'] = pd.to_datetime(oportunidades['Last_Modified_Date'])
oportunidades['Planned_Delivery_Start_Date'] = pd.to_datetime(oportunidades['Planned_Delivery_Start_Date'])
oportunidades['Planned_Delivery_End_Date'] = pd.to_datetime(oportunidades['Planned_Delivery_End_Date'])
oportunidades_japon = (oportunidades.loc[oportunidades['Region'] == 'Japan'])
oportunidades = (oportunidades.loc[oportunidades['Region'] != 'Japan'])
#oportunidades_japon = oportunidades_japon.iloc[:,:3]
oportunidades_japon['Territory'] = oportunidades_japon['Territory'].replace({'None':'Japan'})
oportunidades = pd.concat([oportunidades, oportunidades_japon], axis=0)
oportunidades['Region'] = oportunidades['Region'].replace({'Japan':'APAC', 'Middle East':'EMEA'})
oportunidades[oportunidades.select_dtypes(['object']).columns] = oportunidades.select_dtypes(['object']).apply(lambda x: x.astype('category'))
oportunidades = oportunidades.loc[oportunidades['Territory'] != 'None']
oportunidades = oportunidades.dropna()
oportunidades["Moneda_Convertida"] = (oportunidades['ASP'] / oportunidades['ASP_(converted)'])
oportunidades

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A,Moneda_Convertida
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,2016,NaT,0,USD,83865.6,USD,83865.6,Closed Won,Prod_Category_A_None,1.000000
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,2018,NaT,25,USD,13357192.5,USD,13357192.5,Closed Lost,Prod_Category_A_None,1.000000
5,16802,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,2018,NaT,28,USD,14838277.5,USD,14838277.5,Closed Lost,Prod_Category_A_None,1.000000
7,27455,Americas,NW America,1,1,1,1,0,Bureaucratic_Code_4,2015-04-21,...,2016,NaT,0,USD,50688.0,USD,50688.0,Closed Won,Prod_Category_A_None,1.000000
23,28524,APAC,India,1,1,1,1,0,Bureaucratic_Code_4,2015-10-13,...,2016,NaT,3,USD,1621851.0,USD,1621851.0,Closed Won,Prod_Category_A_None,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16922,18519,APAC,Japan,1,1,1,1,0,Bureaucratic_Code_4,2013-07-28,...,2016,NaT,0,USD,13200.0,USD,6422400.6,Closed Won,Prod_Category_A_None,1.000000
16923,27689,APAC,Japan,1,1,0,0,0,Bureaucratic_Code_4,2015-06-11,...,2016,NaT,0,JPY,12194000.0,JPY,12194000.0,Closed Won,Prod_Category_A_None,111.229165
16924,27688,APAC,Japan,1,1,0,0,0,Bureaucratic_Code_4,2015-06-11,...,2016,NaT,0,JPY,11959500.0,JPY,11959500.0,Closed Won,Prod_Category_A_None,111.229165
16925,19062,APAC,Japan,0,0,0,0,0,Bureaucratic_Code_4,2013-08-11,...,2016,NaT,0,JPY,17537000.0,JPY,17537000.0,Closed Won,Prod_Category_A_None,111.229477
16926,19066,APAC,Japan,1,1,1,1,0,Bureaucratic_Code_4,2013-08-11,...,2016,NaT,0,JPY,13860000.0,JPY,13860000.0,Closed Won,Prod_Category_A_None,111.229550

In [234]:
#Añadimos la columna binaria de si es aprobada o no.

filtro_terminos_entrega = oportunidades['Pricing, Delivery_Terms_Quote_Appr']\
     == oportunidades['Pricing, Delivery_Terms_Approved']

filtro_codigo_burocratico = oportunidades['Bureaucratic_Code_0_Approval']\
     == oportunidades['Bureaucratic_Code_0_Approved']

oportunidades = oportunidades.drop(['Pricing, Delivery_Terms_Quote_Appr'\
    ,'Pricing, Delivery_Terms_Approved', 'Bureaucratic_Code_0_Approval'\
        , 'Bureaucratic_Code_0_Approved', 'Submitted_for_Approval'], axis = 'columns')

oportunidades_posibles = (filtro_terminos_entrega & filtro_codigo_burocratico)

oportunidades.insert(3,'Es_Oportunidad_Posible', oportunidades_posibles)

oportunidades['Es_Oportunidad_Posible'] = oportunidades['Es_Oportunidad_Posible'].replace(
    {True:1, False:0})
oportunidades.head()

,ID,Region,Territory,Es_Oportunidad_Posible,Bureaucratic_Code,Account_Created_Date,Source,Billing_Country,Account_Name,Opportunity_Name,...,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A,Moneda_Convertida
2,27446,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_469,...,2016,NaT,0,USD,83865.6,USD,83865.6,Closed Won,Prod_Category_A_None,1.0
4,16805,Americas,NW America,0,Bureaucratic_Code_5,2013-07-27,Source_11,United States,Account_Name_1201,Opportunity_Name_851,...,2018,NaT,25,USD,13357192.5,USD,13357192.5,Closed Lost,Prod_Category_A_None,1.0
5,16802,Americas,NW America,0,Bureaucratic_Code_5,2013-07-27,Source_11,United States,Account_Name_1201,Opportunity_Name_939,...,2018,NaT,28,USD,14838277.5,USD,14838277.5,Closed Lost,Prod_Category_A_None,1.0
7,27455,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_8227,...,2016,NaT,0,USD,50688.0,USD,50688.0,Closed Won,Prod_Category_A_None,1.0
23,28524,APAC,India,1,Bureaucratic_Code_4,2015-10-13,None,India,Account_Name_1147,Opportunity_Name_7036,...,2016,NaT,3,USD,1621851.0,USD,1621851.0,Closed Won,Prod_Category_A_None,1.0

In [235]:
#Encoding de los vendedores con mean encoding respecto del total amount.
encoding_owners = oportunidades.groupby('Opportunity_Owner').agg({'Total_Amount':'mean'})
encoding_owners.columns = ['Encoding_Vendedor']
encoding_owners = encoding_owners.reset_index()
oportunidades = oportunidades.merge(encoding_owners, how='inner', on='Opportunity_Owner')
oportunidades

,ID,Region,Territory,Es_Oportunidad_Posible,Bureaucratic_Code,Account_Created_Date,Source,Billing_Country,Account_Name,Opportunity_Name,...,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A,Moneda_Convertida,Encoding_Vendedor
0,27446,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_469,...,NaT,0,USD,83865.6,USD,83865.6,Closed Won,Prod_Category_A_None,1.000000,2.232794e+06
1,16805,Americas,NW America,0,Bureaucratic_Code_5,2013-07-27,Source_11,United States,Account_Name_1201,Opportunity_Name_851,...,NaT,25,USD,13357192.5,USD,13357192.5,Closed Lost,Prod_Category_A_None,1.000000,2.232794e+06
2,16802,Americas,NW America,0,Bureaucratic_Code_5,2013-07-27,Source_11,United States,Account_Name_1201,Opportunity_Name_939,...,NaT,28,USD,14838277.5,USD,14838277.5,Closed Lost,Prod_Category_A_None,1.000000,2.232794e+06
3,27455,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_8227,...,NaT,0,USD,50688.0,USD,50688.0,Closed Won,Prod_Category_A_None,1.000000,2.232794e+06
4,21750,Americas,NE America,1,Bureaucratic_Code_4,2013-07-27,Source_11,United States,Account_Name_25,Opportunity_Name_1814,...,NaT,0,USD,11961.6,USD,0.0,Closed Won,Prod_Category_A_None,1.000000,2.232794e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9720,28141,APAC,Japan,1,Bureaucratic_Code_4,2015-07-03,None,Japan,Account_Name_702,Opportunity_Name_4988,...,NaT,1,JPY,38976000.0,JPY,38976000.0,Closed Lost,Prod_Category_A_None,111.229550,5.688996e+07
9721,28084,APAC,Japan,1,Bureaucratic_Code_4,2015-07-03,None,Japan,Account_Name_702,Opportunity_Name_4989,...,NaT,1,JPY,56028000.0,JPY,56028000.0,Closed Lost,Prod_Category_A_None,111.229326,5.688996e+07
9722,28181,APAC,Japan,1,Bureaucratic_Code_1,2015-07-03,None,Japan,Account_Name_702,Opportunity_Name_4994,...,NaT,0,JPY,7660800.0,JPY,7660800.0,Closed Lost,Prod_Category_A_None,111.231449,5.688996e+07
9723,28182,APAC,Japan,1,Bureaucratic_Code_4,2015-07-03,None,Japan,Account_Name_702,Opportunity_Name_8661,...,NaT,0,JPY,825000.0,JPY,825000.0,Closed Won,Prod_Category_A_None,111.230206,5.688996e+07
9724,28164,APAC,Japan,1,Bureaucratic_Code_1,2015-07-03,None,Japan,Account_Name_702,Opportunity_Name_4995,...,NaT,5,JPY,180960000.0,JPY,180960000.0,Closed Lost,Prod_Category_A_None,111.228519,5.688996e+07

In [236]:
#Encoding de los territorios en base al total amount
encoding_territory = oportunidades.groupby('Territory').agg({'Total_Amount' : 'mean'})
encoding_territory.columns = ['Encoding_Territorio']
encoding_territory = encoding_territory.reset_index()
oportunidades = oportunidades.merge(encoding_territory, how='inner', on='Territory')
oportunidades

,ID,Region,Territory,Es_Oportunidad_Posible,Bureaucratic_Code,Account_Created_Date,Source,Billing_Country,Account_Name,Opportunity_Name,...,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A,Moneda_Convertida,Encoding_Vendedor,Encoding_Territorio
0,27446,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_469,...,0,USD,83865.6,USD,83865.6,Closed Won,Prod_Category_A_None,1.0,2.232794e+06,1.534896e+06
1,16805,Americas,NW America,0,Bureaucratic_Code_5,2013-07-27,Source_11,United States,Account_Name_1201,Opportunity_Name_851,...,25,USD,13357192.5,USD,13357192.5,Closed Lost,Prod_Category_A_None,1.0,2.232794e+06,1.534896e+06
2,16802,Americas,NW America,0,Bureaucratic_Code_5,2013-07-27,Source_11,United States,Account_Name_1201,Opportunity_Name_939,...,28,USD,14838277.5,USD,14838277.5,Closed Lost,Prod_Category_A_None,1.0,2.232794e+06,1.534896e+06
3,27455,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_8227,...,0,USD,50688.0,USD,50688.0,Closed Won,Prod_Category_A_None,1.0,2.232794e+06,1.534896e+06
4,21527,Americas,NW America,1,Bureaucratic_Code_4,2013-07-27,Source_11,United States,Account_Name_25,Opportunity_Name_1828,...,0,USD,2814.0,USD,2814.0,Closed Won,Prod_Category_A_None,1.0,2.232794e+06,1.534896e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9720,14862,APAC,New Zealand,0,Bureaucratic_Code_5,2017-05-23,Source_7,New Zealand,Account_Name_1857,Opportunity_Name_11725,...,0,USD,28875.0,USD,147262.5,Closed Won,Prod_Category_A_None,1.0,3.610676e+06,3.498250e+04
9721,14868,APAC,New Zealand,0,Bureaucratic_Code_5,2017-05-23,Source_7,New Zealand,Account_Name_1857,Opportunity_Name_11725,...,0,USD,28875.0,USD,147262.5,Closed Won,Prod_Category_A_None,1.0,3.610676e+06,3.498250e+04
9722,14873,APAC,New Zealand,0,Bureaucratic_Code_5,2017-05-23,Source_7,New Zealand,Account_Name_1857,Opportunity_Name_11725,...,0,USD,28875.0,USD,147262.5,Closed Won,Prod_Category_A_None,1.0,3.610676e+06,3.498250e+04
9723,14879,APAC,New Zealand,0,Bureaucratic_Code_5,2017-05-23,Source_7,New Zealand,Account_Name_1857,Opportunity_Name_11725,...,0,USD,28875.0,USD,147262.5,Closed Won,Prod_Category_A_None,1.0,3.610676e+06,3.498250e+04
9724,23555,EMEA,Egypt,0,Bureaucratic_Code_5,2014-12-10,Source_13,Egypt,Account_Name_1431,Opportunity_Name_341,...,0,USD,9375.0,USD,9375.0,Closed Lost,Prod_Category_A_None,1.0,2.311700e+04,9.375000e+03

In [237]:
#Encoding de las regiones en base al total amount
encoding_region = oportunidades.groupby('Region').agg({'Total_Amount' : 'mean'})
encoding_region.columns = ['Encoding_Region']
encoding_region = encoding_region.reset_index()
oportunidades = oportunidades.merge(encoding_region, how='inner', on='Region')
oportunidades

,ID,Region,Territory,Es_Oportunidad_Posible,Bureaucratic_Code,Account_Created_Date,Source,Billing_Country,Account_Name,Opportunity_Name,...,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A,Moneda_Convertida,Encoding_Vendedor,Encoding_Territorio,Encoding_Region
0,27446,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_469,...,USD,83865.6,USD,83865.6,Closed Won,Prod_Category_A_None,1.0,2.232794e+06,1.534896e+06,2.250980e+06
1,16805,Americas,NW America,0,Bureaucratic_Code_5,2013-07-27,Source_11,United States,Account_Name_1201,Opportunity_Name_851,...,USD,13357192.5,USD,13357192.5,Closed Lost,Prod_Category_A_None,1.0,2.232794e+06,1.534896e+06,2.250980e+06
2,16802,Americas,NW America,0,Bureaucratic_Code_5,2013-07-27,Source_11,United States,Account_Name_1201,Opportunity_Name_939,...,USD,14838277.5,USD,14838277.5,Closed Lost,Prod_Category_A_None,1.0,2.232794e+06,1.534896e+06,2.250980e+06
3,27455,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_8227,...,USD,50688.0,USD,50688.0,Closed Won,Prod_Category_A_None,1.0,2.232794e+06,1.534896e+06,2.250980e+06
4,21527,Americas,NW America,1,Bureaucratic_Code_4,2013-07-27,Source_11,United States,Account_Name_25,Opportunity_Name_1828,...,USD,2814.0,USD,2814.0,Closed Won,Prod_Category_A_None,1.0,2.232794e+06,1.534896e+06,2.250980e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9720,14857,APAC,New Zealand,0,Bureaucratic_Code_5,2017-05-23,Source_7,New Zealand,Account_Name_1857,Opportunity_Name_11725,...,USD,31762.5,USD,147262.5,Closed Won,Prod_Category_A_None,1.0,3.610676e+06,3.498250e+04,2.951944e+06
9721,14862,APAC,New Zealand,0,Bureaucratic_Code_5,2017-05-23,Source_7,New Zealand,Account_Name_1857,Opportunity_Name_11725,...,USD,28875.0,USD,147262.5,Closed Won,Prod_Category_A_None,1.0,3.610676e+06,3.498250e+04,2.951944e+06
9722,14868,APAC,New Zealand,0,Bureaucratic_Code_5,2017-05-23,Source_7,New Zealand,Account_Name_1857,Opportunity_Name_11725,...,USD,28875.0,USD,147262.5,Closed Won,Prod_Category_A_None,1.0,3.610676e+06,3.498250e+04,2.951944e+06
9723,14873,APAC,New Zealand,0,Bureaucratic_Code_5,2017-05-23,Source_7,New Zealand,Account_Name_1857,Opportunity_Name_11725,...,USD,28875.0,USD,147262.5,Closed Won,Prod_Category_A_None,1.0,3.610676e+06,3.498250e+04,2.951944e+06
9724,14879,APAC,New Zealand,0,Bureaucratic_Code_5,2017-05-23,Source_7,New Zealand,Account_Name_1857,Opportunity_Name_11725,...,USD,28875.0,USD,147262.5,Closed Won,Prod_Category_A_None,1.0,3.610676e+06,3.498250e+04,2.951944e+06

In [238]:
#Encoding del tipo de moneda en base al mean del ASP
encoding_moneda = oportunidades.groupby('Total_Amount_Currency').agg({'Moneda_Convertida' : 'mean'})
encoding_moneda.columns = ['Encoding_Moneda']
encoding_moneda = encoding_moneda.reset_index()
oportunidades = oportunidades.merge(encoding_moneda, how='inner', on='Total_Amount_Currency')

In [239]:
#Encoding del Bureaucratic_Code en base a Dummies
oportunidades = pd.concat([oportunidades, pd.get_dummies(oportunidades['Bureaucratic_Code'])], axis='columns')
oportunidades

,ID,Region,Territory,Es_Oportunidad_Posible,Bureaucratic_Code,Account_Created_Date,Source,Billing_Country,Account_Name,Opportunity_Name,...,Encoding_Territorio,Encoding_Region,Encoding_Moneda,Bureaucratic_Code_0,Bureaucratic_Code_1,Bureaucratic_Code_2,Bureaucratic_Code_3,Bureaucratic_Code_4,Bureaucratic_Code_5,Bureaucratic_Code_6
0,27446,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_469,...,1.534896e+06,2.250980e+06,1.000000,0,0,0,0,1,0,0
1,16805,Americas,NW America,0,Bureaucratic_Code_5,2013-07-27,Source_11,United States,Account_Name_1201,Opportunity_Name_851,...,1.534896e+06,2.250980e+06,1.000000,0,0,0,0,0,1,0
2,16802,Americas,NW America,0,Bureaucratic_Code_5,2013-07-27,Source_11,United States,Account_Name_1201,Opportunity_Name_939,...,1.534896e+06,2.250980e+06,1.000000,0,0,0,0,0,1,0
3,27455,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_8227,...,1.534896e+06,2.250980e+06,1.000000,0,0,0,0,1,0,0
4,21527,Americas,NW America,1,Bureaucratic_Code_4,2013-07-27,Source_11,United States,Account_Name_25,Opportunity_Name_1828,...,1.534896e+06,2.250980e+06,1.000000,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9720,17555,APAC,Australia,1,Bureaucratic_Code_4,2013-10-03,None,Australia,Account_Name_1440,Opportunity_Name_10149,...,1.042592e+06,2.951944e+06,1.413202,0,0,0,0,1,0,0
9721,18413,APAC,Australia,1,Bureaucratic_Code_4,2013-07-28,None,Australia,Account_Name_1440,Opportunity_Name_10153,...,1.042592e+06,2.951944e+06,1.413202,0,0,0,0,1,0,0
9722,18416,APAC,Australia,1,Bureaucratic_Code_4,2013-07-28,None,Australia,Account_Name_1440,Opportunity_Name_10150,...,1.042592e+06,2.951944e+06,1.413202,0,0,0,0,1,0,0
9723,22188,APAC,Australia,1,Bureaucratic_Code_4,2014-09-19,Source_9,Australia,Account_Name_1642,Opportunity_Name_10445,...,1.042592e+06,2.951944e+06,1.413202,0,0,0,0,1,0,0
9724,22184,APAC,Australia,0,Bureaucratic_Code_2,2014-09-19,Source_9,Australia,Account_Name_1642,Opportunity_Name_10446,...,1.042592e+06,2.951944e+06,1.413202,0,0,1,0,0,0,0

In [240]:
#Encoding del Billing Country en base a mean de Total_Amount.
encoding_bill_c = oportunidades.groupby('Billing_Country').agg({'Total_Amount' : 'mean'})
encoding_bill_c.columns = ['Encoding_Billing_Country']
encoding_bill_c = encoding_bill_c.reset_index()
oportunidades = oportunidades.merge(encoding_bill_c, how='inner', on='Billing_Country')
oportunidades

,ID,Region,Territory,Es_Oportunidad_Posible,Bureaucratic_Code,Account_Created_Date,Source,Billing_Country,Account_Name,Opportunity_Name,...,Encoding_Region,Encoding_Moneda,Bureaucratic_Code_0,Bureaucratic_Code_1,Bureaucratic_Code_2,Bureaucratic_Code_3,Bureaucratic_Code_4,Bureaucratic_Code_5,Bureaucratic_Code_6,Encoding_Billing_Country
0,27446,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_469,...,2.250980e+06,1.000000,0,0,0,0,1,0,0,2.245889e+06
1,16805,Americas,NW America,0,Bureaucratic_Code_5,2013-07-27,Source_11,United States,Account_Name_1201,Opportunity_Name_851,...,2.250980e+06,1.000000,0,0,0,0,0,1,0,2.245889e+06
2,16802,Americas,NW America,0,Bureaucratic_Code_5,2013-07-27,Source_11,United States,Account_Name_1201,Opportunity_Name_939,...,2.250980e+06,1.000000,0,0,0,0,0,1,0,2.245889e+06
3,27455,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_8227,...,2.250980e+06,1.000000,0,0,0,0,1,0,0,2.245889e+06
4,21527,Americas,NW America,1,Bureaucratic_Code_4,2013-07-27,Source_11,United States,Account_Name_25,Opportunity_Name_1828,...,2.250980e+06,1.000000,0,0,0,0,1,0,0,2.245889e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9720,6773,EMEA,Malta,1,Bureaucratic_Code_4,2017-07-13,Source_13,Malta,Account_Name_600,Opportunity_Name_9426,...,8.201907e+05,0.884131,0,0,0,0,1,0,0,4.164458e+06
9721,6779,EMEA,Malta,1,Bureaucratic_Code_4,2017-07-13,Source_13,Malta,Account_Name_600,Opportunity_Name_9496,...,8.201907e+05,0.884131,0,0,0,0,1,0,0,4.164458e+06
9722,6790,EMEA,Malta,1,Bureaucratic_Code_4,2017-07-13,Source_13,Malta,Account_Name_600,Opportunity_Name_4195,...,8.201907e+05,0.884131,0,0,0,0,1,0,0,4.164458e+06
9723,6762,EMEA,Malta,1,Bureaucratic_Code_4,2017-07-13,Source_13,Malta,Account_Name_600,Opportunity_Name_4194,...,8.201907e+05,0.884131,0,0,0,0,1,0,0,4.164458e+06
9724,6768,EMEA,Malta,1,Bureaucratic_Code_4,2017-07-13,Source_13,Malta,Account_Name_600,Opportunity_Name_4194,...,8.201907e+05,0.884131,0,0,0,0,1,0,0,4.164458e+06

In [241]:
#Encoding del Product_Family en base a mean de Total_Amount.
encoding_product_family = oportunidades.groupby('Product_Family').agg({'Total_Amount' : 'mean'})
encoding_product_family.columns = ['Encoding_Prod_Family']
encoding_product_family = encoding_product_family.reset_index()
oportunidades = oportunidades.merge(encoding_product_family, how='inner', on='Product_Family')
oportunidades

,ID,Region,Territory,Es_Oportunidad_Posible,Bureaucratic_Code,Account_Created_Date,Source,Billing_Country,Account_Name,Opportunity_Name,...,Encoding_Moneda,Bureaucratic_Code_0,Bureaucratic_Code_1,Bureaucratic_Code_2,Bureaucratic_Code_3,Bureaucratic_Code_4,Bureaucratic_Code_5,Bureaucratic_Code_6,Encoding_Billing_Country,Encoding_Prod_Family
0,27446,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_469,...,1.000000,0,0,0,0,1,0,0,2.245889e+06,69490.525
1,27442,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_8543,...,1.000000,0,0,0,0,1,0,0,2.245889e+06,69490.525
2,15713,EMEA,Germany,1,Bureaucratic_Code_4,2013-07-27,None,Germany,Account_Name_1994,Opportunity_Name_12186,...,0.884131,0,0,0,0,1,0,0,8.585832e+05,69490.525
3,16744,EMEA,Spain,1,Bureaucratic_Code_4,2013-07-27,Source_11,Spain,Account_Name_59,Opportunity_Name_9433,...,0.884131,0,0,0,0,1,0,0,1.240120e+06,69490.525
4,15045,APAC,India,0,Bureaucratic_Code_5,2017-05-24,Source_7,India,Account_Name_1983,Opportunity_Name_12179,...,1.000000,0,0,0,0,0,1,0,9.806871e+05,69490.525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9720,9753,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_3358,...,1.000000,0,0,0,0,1,0,0,1.079523e+05,2197.250
9721,9992,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_2744,...,1.000000,0,0,0,0,1,0,0,1.079523e+05,369.600
9722,9859,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_3360,...,1.000000,0,0,0,0,1,0,0,1.079523e+05,2274.300
9723,9163,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_2741,...,1.000000,0,0,0,0,1,0,0,1.079523e+05,3456.000
9724,9136,APAC,China (PRC),0,Bureaucratic_Code_2,2016-01-29,None,China,Account_Name_931,Opportunity_Name_2740,...,1.000000,0,0,1,0,0,0,0,1.079523e+05,35708.750

In [242]:
#Encoding con Dummies de Account_Type

oportunidades = pd.concat([oportunidades, pd.get_dummies(oportunidades['Account_Type'])],axis='columns')
oportunidades

,ID,Region,Territory,Es_Oportunidad_Posible,Bureaucratic_Code,Account_Created_Date,Source,Billing_Country,Account_Name,Opportunity_Name,...,Bureaucratic_Code_6,Encoding_Billing_Country,Encoding_Prod_Family,Account_Type_0,Account_Type_1,Account_Type_2,Account_Type_4,Account_Type_5,Account_Type_6,None
0,27446,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_469,...,0,2.245889e+06,69490.525,0,0,0,0,1,0,0
1,27442,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_8543,...,0,2.245889e+06,69490.525,0,0,0,0,1,0,0
2,15713,EMEA,Germany,1,Bureaucratic_Code_4,2013-07-27,None,Germany,Account_Name_1994,Opportunity_Name_12186,...,0,8.585832e+05,69490.525,1,0,0,0,0,0,0
3,16744,EMEA,Spain,1,Bureaucratic_Code_4,2013-07-27,Source_11,Spain,Account_Name_59,Opportunity_Name_9433,...,0,1.240120e+06,69490.525,1,0,0,0,0,0,0
4,15045,APAC,India,0,Bureaucratic_Code_5,2017-05-24,Source_7,India,Account_Name_1983,Opportunity_Name_12179,...,0,9.806871e+05,69490.525,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9720,9753,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_3358,...,0,1.079523e+05,2197.250,1,0,0,0,0,0,0
9721,9992,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_2744,...,0,1.079523e+05,369.600,1,0,0,0,0,0,0
9722,9859,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_3360,...,0,1.079523e+05,2274.300,1,0,0,0,0,0,0
9723,9163,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_2741,...,0,1.079523e+05,3456.000,1,0,0,0,0,0,0
9724,9136,APAC,China (PRC),0,Bureaucratic_Code_2,2016-01-29,None,China,Account_Name_931,Opportunity_Name_2740,...,0,1.079523e+05,35708.750,1,0,0,0,0,0,0

In [243]:
#Encoding de Delivery Terms en base a Dummies
oportunidades = pd.concat([oportunidades,pd.get_dummies(oportunidades['Delivery_Terms'])],axis='columns')
oportunidades

,ID,Region,Territory,Es_Oportunidad_Posible,Bureaucratic_Code,Account_Created_Date,Source,Billing_Country,Account_Name,Opportunity_Name,...,None,Delivery_Terms_0,Delivery_Terms_1,Delivery_Terms_2,Delivery_Terms_3,Delivery_Terms_4,Delivery_Terms_5,Delivery_Terms_6,Delivery_Terms_7,Delivery_Terms_8
0,27446,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_469,...,0,0,0,0,0,1,0,0,0,0
1,27442,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_8543,...,0,0,0,0,0,1,0,0,0,0
2,15713,EMEA,Germany,1,Bureaucratic_Code_4,2013-07-27,None,Germany,Account_Name_1994,Opportunity_Name_12186,...,0,0,0,1,0,0,0,0,0,0
3,16744,EMEA,Spain,1,Bureaucratic_Code_4,2013-07-27,Source_11,Spain,Account_Name_59,Opportunity_Name_9433,...,0,0,0,1,0,0,0,0,0,0
4,15045,APAC,India,0,Bureaucratic_Code_5,2017-05-24,Source_7,India,Account_Name_1983,Opportunity_Name_12179,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9720,9753,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_3358,...,0,0,0,0,0,0,0,1,0,0
9721,9992,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_2744,...,0,0,0,0,0,0,0,1,0,0
9722,9859,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_3360,...,0,0,0,0,0,0,0,1,0,0
9723,9163,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_2741,...,0,0,0,0,0,0,0,1,0,0
9724,9136,APAC,China (PRC),0,Bureaucratic_Code_2,2016-01-29,None,China,Account_Name_931,Opportunity_Name_2740,...,0,0,0,0,0,0,0,1,0,0

In [244]:
#Obtenemos el año de creación de la oportunidad como columna.
oportunidades['Opportunity_Created_Year'] = oportunidades['Opportunity_Created_Date'].dt.year
oportunidades['Opportunity_Created_Month'] = oportunidades['Opportunity_Created_Date'].dt.month
oportunidades['Año_Por_Mes'] = oportunidades['Opportunity_Created_Year'] \
    * oportunidades['Opportunity_Created_Month']
oportunidades

,ID,Region,Territory,Es_Oportunidad_Posible,Bureaucratic_Code,Account_Created_Date,Source,Billing_Country,Account_Name,Opportunity_Name,...,Delivery_Terms_2,Delivery_Terms_3,Delivery_Terms_4,Delivery_Terms_5,Delivery_Terms_6,Delivery_Terms_7,Delivery_Terms_8,Opportunity_Created_Year,Opportunity_Created_Month,Año_Por_Mes
0,27446,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_469,...,0,0,1,0,0,0,0,2015,12,24180
1,27442,Americas,NW America,1,Bureaucratic_Code_4,2015-04-21,Source_7,United States,Account_Name_1794,Opportunity_Name_8543,...,0,0,1,0,0,0,0,2016,4,8064
2,15713,EMEA,Germany,1,Bureaucratic_Code_4,2013-07-27,None,Germany,Account_Name_1994,Opportunity_Name_12186,...,1,0,0,0,0,0,0,2017,12,24204
3,16744,EMEA,Spain,1,Bureaucratic_Code_4,2013-07-27,Source_11,Spain,Account_Name_59,Opportunity_Name_9433,...,1,0,0,0,0,0,0,2018,1,2018
4,15045,APAC,India,0,Bureaucratic_Code_5,2017-05-24,Source_7,India,Account_Name_1983,Opportunity_Name_12179,...,0,0,0,0,0,0,1,2017,6,12102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9720,9753,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_3358,...,0,0,0,0,1,0,0,2017,12,24204
9721,9992,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_2744,...,0,0,0,0,1,0,0,2018,3,6054
9722,9859,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_3360,...,0,0,0,0,1,0,0,2018,4,8072
9723,9163,APAC,China (PRC),1,Bureaucratic_Code_4,2016-01-29,None,China,Account_Name_931,Opportunity_Name_2741,...,0,0,0,0,1,0,0,2018,6,12108
9724,9136,APAC,China (PRC),0,Bureaucratic_Code_2,2016-01-29,None,China,Account_Name_931,Opportunity_Name_2740,...,0,0,0,0,1,0,0,2018,6,12108

In [245]:
#Una vez que tenemos el dataset limpio como en el TP1, iniciamos con el uso de XGBoost como algoritmo de ML.

#Parametros resultantes del tuning:{'objective': 'reg:logistic', 'max_depth': 7, 'n_estimators': 140, 
#'colsample_bytree': 0.9, 'subsample': 0.9, 'learning_rate': 0.085, 'alpha': 0.01, 'gamma': 0.2}

#Con Error: 0.3574255624906347

params = {
    'objective':'reg:logistic',
    'max_depth':7,
    'n_estimators':450,
    'colsample_bytree':0.4,
    'subsample':0.6,
    'learning_rate':0.02,
    'alpha':0.001,
    #'gamma':0.2
}

params2 = {
    'objective':'reg:logistic',
    'max_depth':8,
    'n_estimators':350,
    'colsample_bytree':0.4,
    'subsample':0.6,
    'learning_rate':0.02,
    'alpha':0.01,
    #'gamma':0.2
}

#xg_reg = xgb.XGBRegressor(objective =params['objective'], 
#                colsample_bytree = params['colsample_bytree'], learning_rate = params['learning_rate'],
#                max_depth = params['max_depth'], alpha = params['alpha'], n_estimators = params['n_estimators'], 
#                gamma = params['gamma'], subsample = params['subsample'])
xg_reg = xgb.XGBRegressor(objective =params['objective'], 
                colsample_bytree = params['colsample_bytree'], learning_rate = params['learning_rate'],
                max_depth = params['max_depth'], alpha = params['alpha'], n_estimators = params['n_estimators'], 
                subsample = params['subsample'])

xg_reg2 = xgb.XGBRegressor(objective =params2['objective'], 
                colsample_bytree = params2['colsample_bytree'], learning_rate = params2['learning_rate'],
                max_depth = params2['max_depth'], alpha = params2['alpha'], n_estimators = params2['n_estimators'], 
                subsample = params2['subsample'])
cat_reg = CatBoostRegressor(border_count = 6, depth = 8, iterations = 1000, l2_leaf_reg = 1, \
                            learning_rate = 0.012, random_strength = 0.9)

y_train = oportunidades['Stage']
oportunidades = oportunidades.loc[(oportunidades['Stage'] == 'Closed Won') | (oportunidades['Stage'] == 'Closed Lost')]
oportunidades['Stage'] = oportunidades['Stage'].replace({'Closed Won': 1, 'Closed Lost': 0})
# std_deviation_amounts = oportunidades.groupby('Opportunity_ID').agg({'TRF':'std'})
# std_deviation_amounts.columns = ['TRF_Std']
# std_deviation_amounts = std_deviation_amounts.reset_index()

#Solo usamos Bureau_Code_ 0,1,2,4,5 porque son los que tiene el set de test.
x_train = oportunidades.groupby('Opportunity_ID').agg({'Año_Por_Mes' : 'mean',\
                                                       'TRF': 'mean',\
                                                      'Encoding_Moneda':'mean', 'Total_Amount': 'sum',\
                                                      'Total_Taxable_Amount':'mean', 'Encoding_Region':'mean',\
                                                      'Encoding_Territorio':'mean','Encoding_Vendedor':'mean',\
                                                      'Es_Oportunidad_Posible':'mean','Stage':'max',\
                                                       'Encoding_Billing_Country':'mean',\
                                                      'Encoding_Prod_Family':'mean'
                                                      })

#x_train = oportunidades.groupby('Opportunity_ID').agg({'Año_Por_Mes' : 'mean',\
 #                                                      'TRF': 'mean',\
  #                                                    'Encoding_Moneda':'mean', 'Total_Amount': 'sum',\
   #                                                   'Total_Taxable_Amount':'mean', 'Encoding_Region':'mean',\
    #                                                  'Encoding_Territorio':'mean','Encoding_Vendedor':'mean',\
     #                                                 'Es_Oportunidad_Posible':'mean','Stage':'max',
       #                                               'Bureaucratic_Code_0':'mean','Bureaucratic_Code_1':'mean',\
      #                                                'Bureaucratic_Code_2':'mean','Bureaucratic_Code_4':'mean',
        #                                              'Bureaucratic_Code_5':'mean', 'Encoding_Billing_Country':'mean',\
         #                                             'Delivery_Terms_0':'mean','Delivery_Terms_1':'mean','Delivery_Terms_2':'mean',\
          #                                            'Delivery_Terms_3':'mean','Delivery_Terms_4':'mean','Delivery_Terms_5':'mean',\
           #                                           'Delivery_Terms_6':'mean','Delivery_Terms_7':'mean','Delivery_Terms_8':'mean',
            #                                          'Encoding_Prod_Family':'mean','Account_Type_0':'mean','Account_Type_1':'mean',\
             #                                         'Account_Type_2':'mean','Account_Type_4':'mean', 'Account_Type_5':'mean'})

x_train = x_train.reset_index()
#x_train = x_train.merge(std_deviation_amounts, on='Opportunity_ID', how='inner')
x_train = x_train.set_index('Opportunity_ID')
y_train = x_train['Stage']
x_train = x_train.drop('Stage', axis='columns')
#x_train['Total_Amount_Std'] = x_train['Total_Amount_Std'].replace({np.nan:0})
x_train['Total_Amount'] = (x_train['Total_Amount'] / x_train['Encoding_Moneda']) 
x_train['Total_Taxable_Amount'] = (x_train['Total_Taxable_Amount'] / x_train['Encoding_Moneda']) 
x_train['Diferencia_Amounts'] = (x_train['Total_Amount'] - x_train['Total_Taxable_Amount'])
x_train = x_train.drop(columns = ['Encoding_Moneda'])
#x_train['Total_Tax_Amount_Std'] = x_train['Total_Tax_Amount_Std'].replace({np.nan:0})
#x_train['TRF_Std'] = x_train['TRF_Std'].replace({np.nan:0})

<ipython-input-245-8fa14878c35f>:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oportunidades['Stage'] = oportunidades['Stage'].replace({'Closed Won': 1, 'Closed Lost': 0})

In [246]:
#Entrenamos al xgboost
xg_reg.fit(x_train, y_train)

xg_reg2.fit(x_train, y_train)

cat_reg.fit(x_train, y_train)

data_dmatrix = xgb.DMatrix(data=x_train,label=y_train)

#xgb.cv(dtrain=data_dmatrix, params=params, nfold=20,
#        num_boost_round=params['n_estimators'], early_stopping_rounds=10,
#        metrics="rmse", as_pandas=True, seed=123)

0:	learn: 0.4913551	total: 2.68ms	remaining: 2.68s
1:	learn: 0.4896066	total: 5.2ms	remaining: 2.59s
2:	learn: 0.4877535	total: 7.53ms	remaining: 2.5s
3:	learn: 0.4864173	total: 8.76ms	remaining: 2.18s
4:	learn: 0.4846320	total: 11.1ms	remaining: 2.21s
5:	learn: 0.4828686	total: 15ms	remaining: 2.48s
6:	learn: 0.4811846	total: 17.7ms	remaining: 2.51s
7:	learn: 0.4793978	total: 21.2ms	remaining: 2.63s
8:	learn: 0.4779285	total: 25.4ms	remaining: 2.79s
9:	learn: 0.4762907	total: 30.2ms	remaining: 2.99s
10:	learn: 0.4749039	total: 33.9ms	remaining: 3.05s
11:	learn: 0.4733998	total: 37.4ms	remaining: 3.08s
12:	learn: 0.4718406	total: 40.4ms	remaining: 3.06s
13:	learn: 0.4702839	total: 42.9ms	remaining: 3.02s
14:	learn: 0.4688090	total: 45.1ms	remaining: 2.96s
15:	learn: 0.4674338	total: 47.4ms	remaining: 2.91s
16:	learn: 0.4660335	total: 49.9ms	remaining: 2.89s
17:	learn: 0.4647628	total: 52ms	remaining: 2.84s
18:	learn: 0.4633965	total: 54.4ms	remaining: 2.81s
19:	learn: 0.4620434	total: 57ms	remaining: 2.79s
20:	learn: 0.4606815	total: 59.4ms	remaining: 2.77s
21:	learn: 0.4593532	total: 61.9ms	remaining: 2.75s
22:	learn: 0.4580497	total: 64.4ms	remaining: 2.73s
23:	learn: 0.4567328	total: 67.2ms	remaining: 2.73s
24:	learn: 0.4555209	total: 69.7ms	remaining: 2.72s
25:	learn: 0.4542047	total: 72.1ms	remaining: 2.7s
26:	learn: 0.4529576	total: 74.6ms	remaining: 2.69s
27:	learn: 0.4518304	total: 77.2ms	remaining: 2.68s
28:	learn: 0.4506689	total: 79.6ms	remaining: 2.67s
29:	learn: 0.4495672	total: 81.9ms	remaining: 2.65s
30:	learn: 0.4483937	total: 84.6ms	remaining: 2.64s
31:	learn: 0.4473383	total: 87.3ms	remaining: 2.64s
32:	learn: 0.4462185	total: 89.9ms	remaining: 2.63s
33:	learn: 0.4451337	total: 92.6ms	remaining: 2.63s
34:	learn: 0.4442088	total: 95.2ms	remaining: 2.63s
35:	learn: 0.4432232	total: 97.8ms	remaining: 2.62s
36:	learn: 0.4422688	total: 100ms	remaining: 2.6s
37:	learn: 0.4410926	total: 103ms	remaining: 2.6s
38:	learn: 0.4401212	total: 105ms	remaining: 2.58s
39:	learn: 0.4392701	total: 107ms	remaining: 2.58s
40:	learn: 0.4383184	total: 110ms	remaining: 2.56s
41:	learn: 0.4374230	total: 112ms	remaining: 2.55s
42:	learn: 0.4365670	total: 114ms	remaining: 2.55s
43:	learn: 0.4356598	total: 117ms	remaining: 2.53s
44:	learn: 0.4348015	total: 119ms	remaining: 2.52s
45:	learn: 0.4341695	total: 121ms	remaining: 2.5s
46:	learn: 0.4332910	total: 123ms	remaining: 2.49s
47:	learn: 0.4323994	total: 125ms	remaining: 2.48s
48:	learn: 0.4314535	total: 127ms	remaining: 2.47s
49:	learn: 0.4308068	total: 129ms	remaining: 2.46s
50:	learn: 0.4300436	total: 132ms	remaining: 2.45s
51:	learn: 0.4293153	total: 134ms	remaining: 2.44s
52:	learn: 0.4286078	total: 136ms	remaining: 2.43s
53:	learn: 0.4277309	total: 139ms	remaining: 2.43s
54:	learn: 0.4270116	total: 141ms	remaining: 2.42s
55:	learn: 0.4262611	total: 143ms	remaining: 2.42s
56:	learn: 0.4256497	total: 145ms	remaining: 2.4s
57:	learn: 0.4249454	total: 147ms	remaining: 2.4s
58:	learn: 0.4241788	total: 150ms	remaining: 2.38s
59:	learn: 0.4236122	total: 152ms	remaining: 2.38s
60:	learn: 0.4230156	total: 155ms	remaining: 2.38s
61:	learn: 0.4223216	total: 157ms	remaining: 2.38s
62:	learn: 0.4215620	total: 159ms	remaining: 2.37s
63:	learn: 0.4209150	total: 162ms	remaining: 2.36s
64:	learn: 0.4202976	total: 164ms	remaining: 2.36s
65:	learn: 0.4197230	total: 166ms	remaining: 2.35s
66:	learn: 0.4189728	total: 169ms	remaining: 2.35s
67:	learn: 0.4183058	total: 171ms	remaining: 2.34s
68:	learn: 0.4177659	total: 174ms	remaining: 2.34s
69:	learn: 0.4172102	total: 178ms	remaining: 2.36s
70:	learn: 0.4168646	total: 179ms	remaining: 2.34s
71:	learn: 0.4162728	total: 182ms	remaining: 2.34s
72:	learn: 0.4156804	total: 185ms	remaining: 2.35s
73:	learn: 0.4151217	total: 187ms	remaining: 2.34s
74:	learn: 0.4144782	total: 190ms	remaining: 2.34s
75:	learn: 0.4138967	total: 192ms	remaining: 2.34s
76:	learn: 0.4133679	total: 195ms	remaining: 2.34s
77:	learn: 0.4128512	total: 197ms	remaining: 2.33s
78:	learn: 0.4124015	total: 200ms	remaining: 2.33s
79:	learn: 0.4118864	total: 202ms	remaining: 2.32s
80:	learn: 0.4113794	total: 205ms	remaining: 2.32s
81:	learn: 0.4108633	total: 208ms	remaining: 2.32s
82:	learn: 0.4103215	total: 210ms	remaining: 2.31s
83:	learn: 0.4098128	total: 212ms	remaining: 2.31s
84:	learn: 0.4093619	total: 215ms	remaining: 2.31s
85:	learn: 0.4089224	total: 218ms	remaining: 2.31s
86:	learn: 0.4086332	total: 220ms	remaining: 2.31s
87:	learn: 0.4081936	total: 224ms	remaining: 2.32s
88:	learn: 0.4077658	total: 228ms	remaining: 2.33s
89:	learn: 0.4073355	total: 232ms	remaining: 2.34s
90:	learn: 0.4069344	total: 236ms	remaining: 2.35s
91:	learn: 0.4064934	total: 240ms	remaining: 2.36s
92:	learn: 0.4061599	total: 244ms	remaining: 2.37s
93:	learn: 0.4056932	total: 246ms	remaining: 2.37s
94:	learn: 0.4053153	total: 249ms	remaining: 2.37s
95:	learn: 0.4049361	total: 258ms	remaining: 2.42s
96:	learn: 0.4045255	total: 262ms	remaining: 2.44s
97:	learn: 0.4041695	total: 265ms	remaining: 2.44s
98:	learn: 0.4037827	total: 269ms	remaining: 2.44s
99:	learn: 0.4033519	total: 272ms	remaining: 2.44s
100:	learn: 0.4029616	total: 276ms	remaining: 2.45s
101:	learn: 0.4025213	total: 279ms	remaining: 2.45s
102:	learn: 0.4022006	total: 282ms	remaining: 2.45s
103:	learn: 0.4017784	total: 285ms	remaining: 2.45s
104:	learn: 0.4014258	total: 288ms	remaining: 2.45s
105:	learn: 0.4010726	total: 291ms	remaining: 2.45s
106:	learn: 0.4007623	total: 294ms	remaining: 2.45s
107:	learn: 0.4004558	total: 297ms	remaining: 2.45s
108:	learn: 0.4001075	total: 300ms	remaining: 2.45s
109:	learn: 0.3997708	total: 303ms	remaining: 2.45s
110:	learn: 0.3993773	total: 306ms	remaining: 2.45s
111:	learn: 0.3990960	total: 309ms	remaining: 2.45s
112:	learn: 0.3987370	total: 313ms	remaining: 2.46s
113:	learn: 0.3983426	total: 316ms	remaining: 2.46s
114:	learn: 0.3979882	total: 320ms	remaining: 2.46s
115:	learn: 0.3976535	total: 323ms	remaining: 2.46s
116:	learn: 0.3974171	total: 327ms	remaining: 2.47s
117:	learn: 0.3971592	total: 332ms	remaining: 2.48s
118:	learn: 0.3968410	total: 336ms	remaining: 2.48s
119:	learn: 0.3965032	total: 340ms	remaining: 2.5s
120:	learn: 0.3962087	total: 344ms	remaining: 2.5s
121:	learn: 0.3959124	total: 347ms	remaining: 2.49s
122:	learn: 0.3956657	total: 349ms	remaining: 2.49s
123:	learn: 0.3954203	total: 351ms	remaining: 2.48s
124:	learn: 0.3952839	total: 354ms	remaining: 2.48s
125:	learn: 0.3950007	total: 358ms	remaining: 2.48s
126:	learn: 0.3947025	total: 365ms	remaining: 2.51s
127:	learn: 0.3944101	total: 370ms	remaining: 2.52s
128:	learn: 0.3941569	total: 372ms	remaining: 2.51s
129:	learn: 0.3938491	total: 376ms	remaining: 2.51s
130:	learn: 0.3935627	total: 381ms	remaining: 2.53s
131:	learn: 0.3932852	total: 385ms	remaining: 2.53s
132:	learn: 0.3930781	total: 390ms	remaining: 2.54s
133:	learn: 0.3929183	total: 393ms	remaining: 2.54s
134:	learn: 0.3926846	total: 397ms	remaining: 2.54s
135:	learn: 0.3924860	total: 401ms	remaining: 2.54s
136:	learn: 0.3922691	total: 407ms	remaining: 2.57s
137:	learn: 0.3919693	total: 411ms	remaining: 2.57s
138:	learn: 0.3917430	total: 414ms	remaining: 2.57s
139:	learn: 0.3914660	total: 417ms	remaining: 2.56s
140:	learn: 0.3912556	total: 419ms	remaining: 2.56s
141:	learn: 0.3910701	total: 422ms	remaining: 2.55s
142:	learn: 0.3908292	total: 426ms	remaining: 2.55s
143:	learn: 0.3906121	total: 429ms	remaining: 2.55s
144:	learn: 0.3903420	total: 433ms	remaining: 2.55s
145:	learn: 0.3900823	total: 438ms	remaining: 2.56s
146:	learn: 0.3898459	total: 441ms	remaining: 2.56s
147:	learn: 0.3896600	total: 445ms	remaining: 2.56s
148:	learn: 0.3894541	total: 449ms	remaining: 2.56s
149:	learn: 0.3892068	total: 452ms	remaining: 2.56s
150:	learn: 0.3889458	total: 456ms	remaining: 2.56s
151:	learn: 0.3887127	total: 460ms	remaining: 2.57s
152:	learn: 0.3884547	total: 463ms	remaining: 2.56s
153:	learn: 0.3882778	total: 466ms	remaining: 2.56s
154:	learn: 0.3880422	total: 469ms	remaining: 2.56s
155:	learn: 0.3877994	total: 473ms	remaining: 2.56s
156:	learn: 0.3875896	total: 477ms	remaining: 2.56s
157:	learn: 0.3873181	total: 481ms	remaining: 2.56s
158:	learn: 0.3870784	total: 486ms	remaining: 2.57s
159:	learn: 0.3868216	total: 490ms	remaining: 2.57s
160:	learn: 0.3866496	total: 493ms	remaining: 2.57s
161:	learn: 0.3864540	total: 497ms	remaining: 2.57s

162:	learn: 0.3862262	total: 502ms	remaining: 2.58s
163:	learn: 0.3860121	total: 507ms	remaining: 2.58s
164:	learn: 0.3858178	total: 511ms	remaining: 2.58s
165:	learn: 0.3856208	total: 517ms	remaining: 2.6s
166:	learn: 0.3854676	total: 520ms	remaining: 2.59s
167:	learn: 0.3852990	total: 523ms	remaining: 2.59s
168:	learn: 0.3850458	total: 527ms	remaining: 2.59s
169:	learn: 0.3849219	total: 530ms	remaining: 2.59s
170:	learn: 0.3847323	total: 534ms	remaining: 2.59s
171:	learn: 0.3845788	total: 537ms	remaining: 2.58s
172:	learn: 0.3844162	total: 541ms	remaining: 2.58s
173:	learn: 0.3842464	total: 544ms	remaining: 2.58s
174:	learn: 0.3841001	total: 547ms	remaining: 2.58s
175:	learn: 0.3839449	total: 552ms	remaining: 2.58s
176:	learn: 0.3838064	total: 554ms	remaining: 2.58s
177:	learn: 0.3836255	total: 557ms	remaining: 2.57s
178:	learn: 0.3835109	total: 560ms	remaining: 2.57s
179:	learn: 0.3834137	total: 563ms	remaining: 2.56s
180:	learn: 0.3832510	total: 565ms	remaining: 2.56s
181:	learn: 0.3831014	total: 568ms	remaining: 2.55s
182:	learn: 0.3829966	total: 572ms	remaining: 2.55s
183:	learn: 0.3827954	total: 575ms	remaining: 2.55s
184:	learn: 0.3826845	total: 578ms	remaining: 2.55s
185:	learn: 0.3826514	total: 580ms	remaining: 2.54s
186:	learn: 0.3824954	total: 583ms	remaining: 2.54s
187:	learn: 0.3823836	total: 586ms	remaining: 2.53s
188:	learn: 0.3822166	total: 588ms	remaining: 2.52s
189:	learn: 0.3820520	total: 591ms	remaining: 2.52s
190:	learn: 0.3818344	total: 594ms	remaining: 2.52s
191:	learn: 0.3816640	total: 597ms	remaining: 2.51s
192:	learn: 0.3815322	total: 599ms	remaining: 2.51s
193:	learn: 0.3813059	total: 602ms	remaining: 2.5s
194:	learn: 0.3811900	total: 605ms	remaining: 2.5s
195:	learn: 0.3810413	total: 607ms	remaining: 2.49s
196:	learn: 0.3809018	total: 610ms	remaining: 2.49s
197:	learn: 0.3807693	total: 615ms	remaining: 2.49s
198:	learn: 0.3806499	total: 618ms	remaining: 2.48s
199:	learn: 0.3805172	total: 620ms	remaining: 2.48s
200:	learn: 0.3803134	total: 623ms	remaining: 2.48s
201:	learn: 0.3801895	total: 626ms	remaining: 2.47s
202:	learn: 0.3800644	total: 629ms	remaining: 2.47s
203:	learn: 0.3798978	total: 632ms	remaining: 2.46s
204:	learn: 0.3797340	total: 635ms	remaining: 2.46s
205:	learn: 0.3796170	total: 640ms	remaining: 2.47s
206:	learn: 0.3794500	total: 643ms	remaining: 2.46s
207:	learn: 0.3793186	total: 646ms	remaining: 2.46s
208:	learn: 0.3792020	total: 649ms	remaining: 2.46s
209:	learn: 0.3790612	total: 651ms	remaining: 2.45s
210:	learn: 0.3790235	total: 653ms	remaining: 2.44s
211:	learn: 0.3789307	total: 656ms	remaining: 2.44s
212:	learn: 0.3788252	total: 658ms	remaining: 2.43s
213:	learn: 0.3786824	total: 661ms	remaining: 2.43s
214:	learn: 0.3785360	total: 664ms	remaining: 2.42s
215:	learn: 0.3783647	total: 668ms	remaining: 2.42s
216:	learn: 0.3782473	total: 670ms	remaining: 2.42s
217:	learn: 0.3781382	total: 672ms	remaining: 2.41s
218:	learn: 0.3780452	total: 675ms	remaining: 2.41s
219:	learn: 0.3778806	total: 678ms	remaining: 2.4s
220:	learn: 0.3777491	total: 680ms	remaining: 2.4s
221:	learn: 0.3776441	total: 683ms	remaining: 2.4s
222:	learn: 0.3775412	total: 686ms	remaining: 2.39s
223:	learn: 0.3774346	total: 689ms	remaining: 2.39s
224:	learn: 0.3772785	total: 692ms	remaining: 2.38s
225:	learn: 0.3771955	total: 694ms	remaining: 2.38s
226:	learn: 0.3771131	total: 696ms	remaining: 2.37s
227:	learn: 0.3770817	total: 698ms	remaining: 2.36s
228:	learn: 0.3769510	total: 700ms	remaining: 2.36s
229:	learn: 0.3768351	total: 703ms	remaining: 2.35s
230:	learn: 0.3767649	total: 706ms	remaining: 2.35s
231:	learn: 0.3766284	total: 709ms	remaining: 2.35s
232:	learn: 0.3764919	total: 712ms	remaining: 2.34s
233:	learn: 0.3764076	total: 714ms	remaining: 2.34s
234:	learn: 0.3763344	total: 716ms	remaining: 2.33s
235:	learn: 0.3761670	total: 719ms	remaining: 2.33s
236:	learn: 0.3760740	total: 722ms	remaining: 2.32s
237:	learn: 0.3759716	total: 724ms	remaining: 2.32s
238:	learn: 0.3758716	total: 726ms	remaining: 2.31s
239:	learn: 0.3757755	total: 728ms	remaining: 2.3s
240:	learn: 0.3756603	total: 730ms	remaining: 2.3s
241:	learn: 0.3755072	total: 733ms	remaining: 2.29s
242:	learn: 0.3753646	total: 735ms	remaining: 2.29s
243:	learn: 0.3752505	total: 737ms	remaining: 2.28s
244:	learn: 0.3751134	total: 739ms	remaining: 2.28s
245:	learn: 0.3749860	total: 741ms	remaining: 2.27s
246:	learn: 0.3748744	total: 744ms	remaining: 2.27s
247:	learn: 0.3747476	total: 746ms	remaining: 2.26s
248:	learn: 0.3746346	total: 749ms	remaining: 2.26s
249:	learn: 0.3745248	total: 751ms	remaining: 2.25s
250:	learn: 0.3744185	total: 753ms	remaining: 2.25s
251:	learn: 0.3743072	total: 755ms	remaining: 2.24s
252:	learn: 0.3742115	total: 758ms	remaining: 2.24s
253:	learn: 0.3740651	total: 760ms	remaining: 2.23s
254:	learn: 0.3739531	total: 762ms	remaining: 2.23s
255:	learn: 0.3738348	total: 764ms	remaining: 2.22s
256:	learn: 0.3737412	total: 767ms	remaining: 2.22s
257:	learn: 0.3736266	total: 770ms	remaining: 2.21s
258:	learn: 0.3734853	total: 772ms	remaining: 2.21s
259:	learn: 0.3734002	total: 774ms	remaining: 2.2s
260:	learn: 0.3733281	total: 777ms	remaining: 2.2s
261:	learn: 0.3732146	total: 779ms	remaining: 2.19s
262:	learn: 0.3731263	total: 782ms	remaining: 2.19s
263:	learn: 0.3730023	total: 784ms	remaining: 2.19s
264:	learn: 0.3728943	total: 786ms	remaining: 2.18s
265:	learn: 0.3727864	total: 789ms	remaining: 2.18s
266:	learn: 0.3726918	total: 791ms	remaining: 2.17s
267:	learn: 0.3725679	total: 793ms	remaining: 2.17s
268:	learn: 0.3724907	total: 796ms	remaining: 2.16s
269:	learn: 0.3723790	total: 798ms	remaining: 2.16s
270:	learn: 0.3723172	total: 800ms	remaining: 2.15s
271:	learn: 0.3722126	total: 803ms	remaining: 2.15s
272:	learn: 0.3721243	total: 805ms	remaining: 2.14s
273:	learn: 0.3720484	total: 807ms	remaining: 2.14s
274:	learn: 0.3719532	total: 810ms	remaining: 2.13s
275:	learn: 0.3717853	total: 813ms	remaining: 2.13s
276:	learn: 0.3716829	total: 815ms	remaining: 2.13s
277:	learn: 0.3715692	total: 818ms	remaining: 2.12s
278:	learn: 0.3714377	total: 821ms	remaining: 2.12s
279:	learn: 0.3713296	total: 823ms	remaining: 2.12s
280:	learn: 0.3712311	total: 826ms	remaining: 2.11s
281:	learn: 0.3711323	total: 828ms	remaining: 2.11s
282:	learn: 0.3710442	total: 835ms	remaining: 2.12s
283:	learn: 0.3709535	total: 839ms	remaining: 2.12s
284:	learn: 0.3708744	total: 842ms	remaining: 2.11s
285:	learn: 0.3707720	total: 844ms	remaining: 2.11s
286:	learn: 0.3706790	total: 847ms	remaining: 2.1s
287:	learn: 0.3706015	total: 849ms	remaining: 2.1s
288:	learn: 0.3704629	total: 852ms	remaining: 2.1s
289:	learn: 0.3703789	total: 855ms	remaining: 2.09s
290:	learn: 0.3703154	total: 858ms	remaining: 2.09s
291:	learn: 0.3702402	total: 862ms	remaining: 2.09s
292:	learn: 0.3701104	total: 871ms	remaining: 2.1s
293:	learn: 0.3700499	total: 875ms	remaining: 2.1s
294:	learn: 0.3699872	total: 878ms	remaining: 2.1s
295:	learn: 0.3698681	total: 881ms	remaining: 2.1s
296:	learn: 0.3697699	total: 886ms	remaining: 2.1s
297:	learn: 0.3697031	total: 889ms	remaining: 2.1s
298:	learn: 0.3695733	total: 893ms	remaining: 2.09s
299:	learn: 0.3695179	total: 897ms	remaining: 2.09s
300:	learn: 0.3693845	total: 905ms	remaining: 2.1s
301:	learn: 0.3692880	total: 908ms	remaining: 2.1s
302:	learn: 0.3692192	total: 914ms	remaining: 2.1s
303:	learn: 0.3691163	total: 917ms	remaining: 2.1s
304:	learn: 0.3690035	total: 921ms	remaining: 2.1s
305:	learn: 0.3689393	total: 925ms	remaining: 2.1s
306:	learn: 0.3688481	total: 931ms	remaining: 2.1s
307:	learn: 0.3687331	total: 939ms	remaining: 2.11s
308:	learn: 0.3686601	total: 941ms	remaining: 2.1s
309:	learn: 0.3685620	total: 945ms	remaining: 2.1s
310:	learn: 0.3684826	total: 948ms	remaining: 2.1s
311:	learn: 0.3684105	total: 951ms	remaining: 2.1s
312:	learn: 0.3682955	total: 953ms	remaining: 2.09s
313:	learn: 0.3682039	total: 956ms	remaining: 2.09s
314:	learn: 0.3681231	total: 959ms	remaining: 2.08s
315:	learn: 0.3680578	total: 962ms	remaining: 2.08s
316:	learn: 0.3679893	total: 966ms	remaining: 2.08s
317:	learn: 0.3679013	total: 969ms	remaining: 2.08s
318:	learn: 0.3678225	total: 972ms	remaining: 2.08s
319:	learn: 0.3677679	total: 975ms	remaining: 2.07s
320:	learn: 0.3676763	total: 978ms	remaining: 2.07s
321:	learn: 0.3675947	total: 980ms	remaining: 2.06s
322:	learn: 0.3675002	total: 983ms	remaining: 2.06s
323:	learn: 0.3674151	total: 986ms	remaining: 2.06s
324:	learn: 0.3673039	total: 989ms	remaining: 2.05s
325:	learn: 0.3671658	total: 993ms	remaining: 2.05s
326:	learn: 0.3670910	total: 997ms	remaining: 2.05s
327:	learn: 0.3670356	total: 1000ms	remaining: 2.05s

328:	learn: 0.3669456	total: 1s	remaining: 2.05s
329:	learn: 0.3668658	total: 1.01s	remaining: 2.05s
330:	learn: 0.3668015	total: 1.01s	remaining: 2.04s
331:	learn: 0.3667066	total: 1.01s	remaining: 2.04s
332:	learn: 0.3666297	total: 1.02s	remaining: 2.04s
333:	learn: 0.3665561	total: 1.02s	remaining: 2.04s
334:	learn: 0.3664409	total: 1.03s	remaining: 2.04s
335:	learn: 0.3663496	total: 1.03s	remaining: 2.04s
336:	learn: 0.3662919	total: 1.03s	remaining: 2.03s
337:	learn: 0.3662518	total: 1.04s	remaining: 2.03s
338:	learn: 0.3661925	total: 1.04s	remaining: 2.03s
339:	learn: 0.3661023	total: 1.04s	remaining: 2.03s
340:	learn: 0.3660127	total: 1.05s	remaining: 2.03s
341:	learn: 0.3659044	total: 1.05s	remaining: 2.03s
342:	learn: 0.3658402	total: 1.06s	remaining: 2.03s
343:	learn: 0.3657635	total: 1.06s	remaining: 2.03s
344:	learn: 0.3656724	total: 1.07s	remaining: 2.02s
345:	learn: 0.3655958	total: 1.07s	remaining: 2.02s
346:	learn: 0.3655337	total: 1.07s	remaining: 2.02s
347:	learn: 0.3654334	total: 1.08s	remaining: 2.02s
348:	learn: 0.3653721	total: 1.08s	remaining: 2.02s
349:	learn: 0.3652948	total: 1.08s	remaining: 2.02s
350:	learn: 0.3652223	total: 1.09s	remaining: 2.01s
351:	learn: 0.3651572	total: 1.09s	remaining: 2.01s
352:	learn: 0.3650385	total: 1.09s	remaining: 2s
353:	learn: 0.3649486	total: 1.09s	remaining: 2s
354:	learn: 0.3648363	total: 1.1s	remaining: 1.99s
355:	learn: 0.3647930	total: 1.1s	remaining: 1.99s
356:	learn: 0.3646874	total: 1.1s	remaining: 1.99s
357:	learn: 0.3646172	total: 1.11s	remaining: 1.98s
358:	learn: 0.3645512	total: 1.11s	remaining: 1.98s
359:	learn: 0.3644910	total: 1.11s	remaining: 1.98s
360:	learn: 0.3644206	total: 1.11s	remaining: 1.97s
361:	learn: 0.3643746	total: 1.12s	remaining: 1.98s
362:	learn: 0.3642986	total: 1.13s	remaining: 1.98s
363:	learn: 0.3641827	total: 1.13s	remaining: 1.97s
364:	learn: 0.3641028	total: 1.13s	remaining: 1.97s
365:	learn: 0.3640160	total: 1.13s	remaining: 1.96s
366:	learn: 0.3639408	total: 1.14s	remaining: 1.96s
367:	learn: 0.3638991	total: 1.14s	remaining: 1.95s
368:	learn: 0.3638177	total: 1.14s	remaining: 1.95s
369:	learn: 0.3637274	total: 1.14s	remaining: 1.95s
370:	learn: 0.3636690	total: 1.15s	remaining: 1.94s
371:	learn: 0.3635704	total: 1.15s	remaining: 1.94s
372:	learn: 0.3634874	total: 1.15s	remaining: 1.93s
373:	learn: 0.3634175	total: 1.15s	remaining: 1.93s
374:	learn: 0.3633004	total: 1.15s	remaining: 1.92s
375:	learn: 0.3632298	total: 1.16s	remaining: 1.92s
376:	learn: 0.3631421	total: 1.16s	remaining: 1.92s
377:	learn: 0.3630664	total: 1.16s	remaining: 1.91s
378:	learn: 0.3630021	total: 1.17s	remaining: 1.91s
379:	learn: 0.3629583	total: 1.17s	remaining: 1.91s
380:	learn: 0.3628907	total: 1.17s	remaining: 1.9s
381:	learn: 0.3628096	total: 1.17s	remaining: 1.9s
382:	learn: 0.3627199	total: 1.18s	remaining: 1.9s
383:	learn: 0.3626482	total: 1.18s	remaining: 1.89s
384:	learn: 0.3625692	total: 1.18s	remaining: 1.89s
385:	learn: 0.3624851	total: 1.19s	remaining: 1.89s
386:	learn: 0.3624224	total: 1.19s	remaining: 1.88s
387:	learn: 0.3623428	total: 1.19s	remaining: 1.88s
388:	learn: 0.3622331	total: 1.2s	remaining: 1.88s
389:	learn: 0.3621413	total: 1.2s	remaining: 1.88s
390:	learn: 0.3620758	total: 1.2s	remaining: 1.87s
391:	learn: 0.3620169	total: 1.21s	remaining: 1.87s
392:	learn: 0.3619308	total: 1.21s	remaining: 1.87s
393:	learn: 0.3618487	total: 1.21s	remaining: 1.86s
394:	learn: 0.3617723	total: 1.21s	remaining: 1.86s
395:	learn: 0.3617103	total: 1.22s	remaining: 1.85s
396:	learn: 0.3616255	total: 1.22s	remaining: 1.85s
397:	learn: 0.3615611	total: 1.22s	remaining: 1.85s
398:	learn: 0.3615143	total: 1.22s	remaining: 1.84s
399:	learn: 0.3614305	total: 1.23s	remaining: 1.84s
400:	learn: 0.3613087	total: 1.23s	remaining: 1.84s
401:	learn: 0.3612458	total: 1.23s	remaining: 1.83s
402:	learn: 0.3611944	total: 1.23s	remaining: 1.83s
403:	learn: 0.3611139	total: 1.24s	remaining: 1.82s
404:	learn: 0.3610200	total: 1.24s	remaining: 1.82s
405:	learn: 0.3609395	total: 1.24s	remaining: 1.81s
406:	learn: 0.3608922	total: 1.24s	remaining: 1.81s
407:	learn: 0.3608507	total: 1.25s	remaining: 1.81s
408:	learn: 0.3607671	total: 1.25s	remaining: 1.8s
409:	learn: 0.3607152	total: 1.25s	remaining: 1.8s
410:	learn: 0.3606327	total: 1.25s	remaining: 1.79s
411:	learn: 0.3605223	total: 1.25s	remaining: 1.79s
412:	learn: 0.3604278	total: 1.26s	remaining: 1.79s
413:	learn: 0.3603391	total: 1.26s	remaining: 1.78s
414:	learn: 0.3602345	total: 1.26s	remaining: 1.78s
415:	learn: 0.3601699	total: 1.26s	remaining: 1.78s
416:	learn: 0.3601216	total: 1.27s	remaining: 1.77s
417:	learn: 0.3600187	total: 1.27s	remaining: 1.77s
418:	learn: 0.3599555	total: 1.27s	remaining: 1.76s
419:	learn: 0.3598486	total: 1.27s	remaining: 1.76s
420:	learn: 0.3597977	total: 1.28s	remaining: 1.75s
421:	learn: 0.3597144	total: 1.28s	remaining: 1.75s
422:	learn: 0.3596525	total: 1.28s	remaining: 1.75s
423:	learn: 0.3595951	total: 1.28s	remaining: 1.74s
424:	learn: 0.3595237	total: 1.28s	remaining: 1.74s
425:	learn: 0.3594410	total: 1.29s	remaining: 1.73s
426:	learn: 0.3593701	total: 1.29s	remaining: 1.73s
427:	learn: 0.3593024	total: 1.29s	remaining: 1.73s
428:	learn: 0.3592319	total: 1.29s	remaining: 1.72s
429:	learn: 0.3591702	total: 1.3s	remaining: 1.72s
430:	learn: 0.3590903	total: 1.3s	remaining: 1.71s
431:	learn: 0.3590005	total: 1.3s	remaining: 1.71s
432:	learn: 0.3589112	total: 1.3s	remaining: 1.71s
433:	learn: 0.3588445	total: 1.3s	remaining: 1.7s
434:	learn: 0.3587943	total: 1.31s	remaining: 1.7s
435:	learn: 0.3587336	total: 1.31s	remaining: 1.7s
436:	learn: 0.3586611	total: 1.31s	remaining: 1.69s
437:	learn: 0.3586008	total: 1.31s	remaining: 1.69s
438:	learn: 0.3585369	total: 1.32s	remaining: 1.68s
439:	learn: 0.3584665	total: 1.32s	remaining: 1.68s
440:	learn: 0.3583834	total: 1.32s	remaining: 1.68s
441:	learn: 0.3583253	total: 1.32s	remaining: 1.67s
442:	learn: 0.3582363	total: 1.33s	remaining: 1.67s
443:	learn: 0.3581745	total: 1.33s	remaining: 1.66s
444:	learn: 0.3580867	total: 1.33s	remaining: 1.66s
445:	learn: 0.3580404	total: 1.33s	remaining: 1.66s
446:	learn: 0.3579899	total: 1.33s	remaining: 1.65s
447:	learn: 0.3579043	total: 1.34s	remaining: 1.65s
448:	learn: 0.3578350	total: 1.34s	remaining: 1.65s
449:	learn: 0.3577424	total: 1.34s	remaining: 1.64s
450:	learn: 0.3576735	total: 1.35s	remaining: 1.64s
451:	learn: 0.3576675	total: 1.35s	remaining: 1.63s
452:	learn: 0.3575700	total: 1.35s	remaining: 1.63s
453:	learn: 0.3575044	total: 1.35s	remaining: 1.63s
454:	learn: 0.3574300	total: 1.35s	remaining: 1.62s
455:	learn: 0.3573248	total: 1.36s	remaining: 1.62s
456:	learn: 0.3572245	total: 1.36s	remaining: 1.62s
457:	learn: 0.3571393	total: 1.36s	remaining: 1.61s
458:	learn: 0.3570823	total: 1.37s	remaining: 1.61s
459:	learn: 0.3569959	total: 1.37s	remaining: 1.61s
460:	learn: 0.3569183	total: 1.37s	remaining: 1.6s
461:	learn: 0.3569161	total: 1.37s	remaining: 1.6s
462:	learn: 0.3568543	total: 1.38s	remaining: 1.6s
463:	learn: 0.3568068	total: 1.38s	remaining: 1.59s
464:	learn: 0.3567428	total: 1.38s	remaining: 1.59s
465:	learn: 0.3566615	total: 1.39s	remaining: 1.59s
466:	learn: 0.3566197	total: 1.39s	remaining: 1.59s
467:	learn: 0.3565663	total: 1.4s	remaining: 1.59s
468:	learn: 0.3565618	total: 1.4s	remaining: 1.58s
469:	learn: 0.3565110	total: 1.4s	remaining: 1.58s
470:	learn: 0.3563904	total: 1.4s	remaining: 1.58s
471:	learn: 0.3563418	total: 1.41s	remaining: 1.57s
472:	learn: 0.3562920	total: 1.41s	remaining: 1.57s
473:	learn: 0.3562437	total: 1.41s	remaining: 1.56s
474:	learn: 0.3561862	total: 1.41s	remaining: 1.56s
475:	learn: 0.3561316	total: 1.42s	remaining: 1.56s
476:	learn: 0.3560678	total: 1.42s	remaining: 1.55s
477:	learn: 0.3559915	total: 1.42s	remaining: 1.55s
478:	learn: 0.3559235	total: 1.42s	remaining: 1.55s
479:	learn: 0.3558673	total: 1.43s	remaining: 1.54s
480:	learn: 0.3557814	total: 1.43s	remaining: 1.54s
481:	learn: 0.3557068	total: 1.43s	remaining: 1.54s
482:	learn: 0.3556550	total: 1.43s	remaining: 1.53s
483:	learn: 0.3555779	total: 1.44s	remaining: 1.53s
484:	learn: 0.3555108	total: 1.44s	remaining: 1.53s
485:	learn: 0.3554772	total: 1.44s	remaining: 1.52s
486:	learn: 0.3553928	total: 1.45s	remaining: 1.52s
487:	learn: 0.3553188	total: 1.45s	remaining: 1.52s
488:	learn: 0.3552623	total: 1.45s	remaining: 1.52s
489:	learn: 0.3552102	total: 1.46s	remaining: 1.51s
490:	learn: 0.3551018	total: 1.46s	remaining: 1.51s
491:	learn: 0.3550298	total: 1.46s	remaining: 1.51s
492:	learn: 0.3549543	total: 1.47s	remaining: 1.51s
493:	learn: 0.3549022	total: 1.47s	remaining: 1.5s
494:	learn: 0.3548534	total: 1.47s	remaining: 1.5s
495:	learn: 0.3547665	total: 1.47s	remaining: 1.5s
496:	learn: 0.3547261	total: 1.48s	remaining: 1.5s
497:	learn: 0.3546882	total: 1.48s	remaining: 1.49s
498:	learn: 0.3546236	total: 1.48s	remaining: 1.49s
499:	learn: 0.3545658	total: 1.49s	remaining: 1.49s
500:	learn: 0.3545089	total: 1.49s	remaining: 1.48s
501:	learn: 0.3544416	total: 1.49s	remaining: 1.48s
502:	learn: 0.3544108	total: 1.49s	remaining: 1.48s
503:	learn: 0.3543500	total: 1.5s	remaining: 1.47s
504:	learn: 0.3543013	total: 1.5s	remaining: 1.47s
505:	learn: 0.3542318	total: 1.5s	remaining: 1.47s

506:	learn: 0.3541634	total: 1.51s	remaining: 1.47s
507:	learn: 0.3540930	total: 1.51s	remaining: 1.46s
508:	learn: 0.3540279	total: 1.51s	remaining: 1.46s
509:	learn: 0.3539776	total: 1.52s	remaining: 1.46s
510:	learn: 0.3539197	total: 1.52s	remaining: 1.45s
511:	learn: 0.3538234	total: 1.52s	remaining: 1.45s
512:	learn: 0.3537616	total: 1.52s	remaining: 1.45s
513:	learn: 0.3536968	total: 1.53s	remaining: 1.44s
514:	learn: 0.3536174	total: 1.53s	remaining: 1.44s
515:	learn: 0.3535633	total: 1.53s	remaining: 1.44s
516:	learn: 0.3535185	total: 1.54s	remaining: 1.44s
517:	learn: 0.3534600	total: 1.54s	remaining: 1.43s
518:	learn: 0.3534046	total: 1.54s	remaining: 1.43s
519:	learn: 0.3533001	total: 1.55s	remaining: 1.43s
520:	learn: 0.3532153	total: 1.55s	remaining: 1.43s
521:	learn: 0.3531489	total: 1.56s	remaining: 1.43s
522:	learn: 0.3530656	total: 1.56s	remaining: 1.42s
523:	learn: 0.3530174	total: 1.57s	remaining: 1.42s
524:	learn: 0.3529861	total: 1.57s	remaining: 1.42s
525:	learn: 0.3529157	total: 1.57s	remaining: 1.42s
526:	learn: 0.3528391	total: 1.58s	remaining: 1.42s
527:	learn: 0.3528055	total: 1.59s	remaining: 1.42s
528:	learn: 0.3527206	total: 1.59s	remaining: 1.42s
529:	learn: 0.3526509	total: 1.6s	remaining: 1.42s
530:	learn: 0.3526304	total: 1.6s	remaining: 1.41s
531:	learn: 0.3525787	total: 1.6s	remaining: 1.41s
532:	learn: 0.3525225	total: 1.61s	remaining: 1.41s
533:	learn: 0.3524635	total: 1.61s	remaining: 1.41s
534:	learn: 0.3523942	total: 1.62s	remaining: 1.41s
535:	learn: 0.3523574	total: 1.63s	remaining: 1.41s
536:	learn: 0.3522812	total: 1.63s	remaining: 1.41s
537:	learn: 0.3522441	total: 1.63s	remaining: 1.4s
538:	learn: 0.3522031	total: 1.65s	remaining: 1.41s
539:	learn: 0.3521641	total: 1.65s	remaining: 1.41s
540:	learn: 0.3520951	total: 1.66s	remaining: 1.41s
541:	learn: 0.3520469	total: 1.66s	remaining: 1.41s
542:	learn: 0.3520023	total: 1.67s	remaining: 1.4s
543:	learn: 0.3519108	total: 1.67s	remaining: 1.4s
544:	learn: 0.3518427	total: 1.68s	remaining: 1.4s
545:	learn: 0.3518046	total: 1.68s	remaining: 1.4s
546:	learn: 0.3517523	total: 1.69s	remaining: 1.4s
547:	learn: 0.3516978	total: 1.69s	remaining: 1.39s
548:	learn: 0.3516624	total: 1.69s	remaining: 1.39s
549:	learn: 0.3515795	total: 1.7s	remaining: 1.39s
550:	learn: 0.3515397	total: 1.7s	remaining: 1.39s
551:	learn: 0.3514822	total: 1.71s	remaining: 1.38s
552:	learn: 0.3514079	total: 1.71s	remaining: 1.38s
553:	learn: 0.3513247	total: 1.71s	remaining: 1.38s
554:	learn: 0.3512434	total: 1.71s	remaining: 1.37s
555:	learn: 0.3511644	total: 1.72s	remaining: 1.37s
556:	learn: 0.3511072	total: 1.72s	remaining: 1.37s
557:	learn: 0.3510701	total: 1.73s	remaining: 1.37s
558:	learn: 0.3509815	total: 1.73s	remaining: 1.36s
559:	learn: 0.3508986	total: 1.73s	remaining: 1.36s
560:	learn: 0.3508405	total: 1.74s	remaining: 1.36s
561:	learn: 0.3507771	total: 1.75s	remaining: 1.36s
562:	learn: 0.3507326	total: 1.75s	remaining: 1.36s
563:	learn: 0.3506798	total: 1.76s	remaining: 1.36s
564:	learn: 0.3506217	total: 1.76s	remaining: 1.35s
565:	learn: 0.3506197	total: 1.76s	remaining: 1.35s
566:	learn: 0.3505943	total: 1.76s	remaining: 1.35s
567:	learn: 0.3505387	total: 1.77s	remaining: 1.34s
568:	learn: 0.3504665	total: 1.77s	remaining: 1.34s
569:	learn: 0.3504022	total: 1.77s	remaining: 1.34s
570:	learn: 0.3503244	total: 1.77s	remaining: 1.33s
571:	learn: 0.3502877	total: 1.78s	remaining: 1.33s
572:	learn: 0.3502465	total: 1.78s	remaining: 1.33s
573:	learn: 0.3502127	total: 1.78s	remaining: 1.32s
574:	learn: 0.3501557	total: 1.78s	remaining: 1.32s
575:	learn: 0.3500977	total: 1.79s	remaining: 1.32s
576:	learn: 0.3500930	total: 1.79s	remaining: 1.31s
577:	learn: 0.3500292	total: 1.79s	remaining: 1.31s
578:	learn: 0.3499735	total: 1.8s	remaining: 1.31s
579:	learn: 0.3498974	total: 1.8s	remaining: 1.3s
580:	learn: 0.3498539	total: 1.8s	remaining: 1.3s
581:	learn: 0.3498243	total: 1.81s	remaining: 1.3s
582:	learn: 0.3497582	total: 1.81s	remaining: 1.3s
583:	learn: 0.3497073	total: 1.82s	remaining: 1.29s
584:	learn: 0.3496705	total: 1.82s	remaining: 1.29s
585:	learn: 0.3496121	total: 1.82s	remaining: 1.29s
586:	learn: 0.3495667	total: 1.83s	remaining: 1.28s
587:	learn: 0.3495191	total: 1.83s	remaining: 1.28s
588:	learn: 0.3494410	total: 1.83s	remaining: 1.28s
589:	learn: 0.3494023	total: 1.83s	remaining: 1.27s
590:	learn: 0.3493573	total: 1.84s	remaining: 1.27s
591:	learn: 0.3492719	total: 1.84s	remaining: 1.27s
592:	learn: 0.3492298	total: 1.85s	remaining: 1.27s
593:	learn: 0.3491826	total: 1.85s	remaining: 1.26s
594:	learn: 0.3491515	total: 1.85s	remaining: 1.26s
595:	learn: 0.3490618	total: 1.85s	remaining: 1.26s
596:	learn: 0.3490274	total: 1.86s	remaining: 1.25s
597:	learn: 0.3489484	total: 1.86s	remaining: 1.25s
598:	learn: 0.3489079	total: 1.86s	remaining: 1.25s
599:	learn: 0.3488589	total: 1.86s	remaining: 1.24s
600:	learn: 0.3488125	total: 1.87s	remaining: 1.24s
601:	learn: 0.3487775	total: 1.87s	remaining: 1.24s
602:	learn: 0.3487054	total: 1.87s	remaining: 1.23s
603:	learn: 0.3486674	total: 1.88s	remaining: 1.23s
604:	learn: 0.3485918	total: 1.88s	remaining: 1.23s
605:	learn: 0.3485183	total: 1.88s	remaining: 1.22s
606:	learn: 0.3484805	total: 1.89s	remaining: 1.22s
607:	learn: 0.3484418	total: 1.89s	remaining: 1.22s
608:	learn: 0.3483885	total: 1.89s	remaining: 1.21s
609:	learn: 0.3483281	total: 1.89s	remaining: 1.21s
610:	learn: 0.3482747	total: 1.9s	remaining: 1.21s
611:	learn: 0.3482412	total: 1.9s	remaining: 1.2s
612:	learn: 0.3481702	total: 1.9s	remaining: 1.2s
613:	learn: 0.3481114	total: 1.9s	remaining: 1.2s
614:	learn: 0.3480651	total: 1.91s	remaining: 1.19s
615:	learn: 0.3480096	total: 1.91s	remaining: 1.19s
616:	learn: 0.3479364	total: 1.91s	remaining: 1.19s
617:	learn: 0.3478839	total: 1.92s	remaining: 1.18s
618:	learn: 0.3478288	total: 1.92s	remaining: 1.18s
619:	learn: 0.3477644	total: 1.92s	remaining: 1.18s
620:	learn: 0.3477329	total: 1.92s	remaining: 1.17s
621:	learn: 0.3476949	total: 1.93s	remaining: 1.17s
622:	learn: 0.3476201	total: 1.93s	remaining: 1.17s
623:	learn: 0.3475284	total: 1.93s	remaining: 1.16s
624:	learn: 0.3474886	total: 1.94s	remaining: 1.16s
625:	learn: 0.3474513	total: 1.94s	remaining: 1.16s
626:	learn: 0.3474010	total: 1.94s	remaining: 1.15s
627:	learn: 0.3473603	total: 1.94s	remaining: 1.15s
628:	learn: 0.3473182	total: 1.95s	remaining: 1.15s
629:	learn: 0.3472630	total: 1.95s	remaining: 1.14s
630:	learn: 0.3472142	total: 1.95s	remaining: 1.14s
631:	learn: 0.3471664	total: 1.96s	remaining: 1.14s
632:	learn: 0.3470963	total: 1.97s	remaining: 1.14s
633:	learn: 0.3470594	total: 1.97s	remaining: 1.14s
634:	learn: 0.3470155	total: 1.97s	remaining: 1.13s
635:	learn: 0.3469777	total: 1.98s	remaining: 1.13s
636:	learn: 0.3469204	total: 1.98s	remaining: 1.13s
637:	learn: 0.3468679	total: 1.98s	remaining: 1.12s
638:	learn: 0.3468264	total: 1.98s	remaining: 1.12s
639:	learn: 0.3467519	total: 1.99s	remaining: 1.12s
640:	learn: 0.3466941	total: 1.99s	remaining: 1.11s
641:	learn: 0.3466599	total: 1.99s	remaining: 1.11s
642:	learn: 0.3466301	total: 2s	remaining: 1.11s
643:	learn: 0.3465681	total: 2s	remaining: 1.11s
644:	learn: 0.3465302	total: 2.01s	remaining: 1.1s
645:	learn: 0.3464754	total: 2.01s	remaining: 1.1s
646:	learn: 0.3464152	total: 2.01s	remaining: 1.1s
647:	learn: 0.3463618	total: 2.02s	remaining: 1.1s
648:	learn: 0.3463089	total: 2.02s	remaining: 1.09s
649:	learn: 0.3462498	total: 2.03s	remaining: 1.09s
650:	learn: 0.3462026	total: 2.03s	remaining: 1.09s
651:	learn: 0.3461328	total: 2.03s	remaining: 1.08s
652:	learn: 0.3460661	total: 2.04s	remaining: 1.08s
653:	learn: 0.3459932	total: 2.04s	remaining: 1.08s
654:	learn: 0.3459339	total: 2.04s	remaining: 1.07s
655:	learn: 0.3458744	total: 2.04s	remaining: 1.07s
656:	learn: 0.3458270	total: 2.05s	remaining: 1.07s
657:	learn: 0.3458069	total: 2.05s	remaining: 1.07s
658:	learn: 0.3457391	total: 2.06s	remaining: 1.06s
659:	learn: 0.3456605	total: 2.06s	remaining: 1.06s
660:	learn: 0.3456204	total: 2.07s	remaining: 1.06s
661:	learn: 0.3455881	total: 2.07s	remaining: 1.06s
662:	learn: 0.3455486	total: 2.07s	remaining: 1.05s
663:	learn: 0.3454824	total: 2.08s	remaining: 1.05s
664:	learn: 0.3454309	total: 2.08s	remaining: 1.05s
665:	learn: 0.3453472	total: 2.08s	remaining: 1.04s
666:	learn: 0.3453114	total: 2.08s	remaining: 1.04s
667:	learn: 0.3452575	total: 2.09s	remaining: 1.04s
668:	learn: 0.3451932	total: 2.09s	remaining: 1.03s
669:	learn: 0.3451536	total: 2.1s	remaining: 1.03s
670:	learn: 0.3451011	total: 2.1s	remaining: 1.03s
671:	learn: 0.3450341	total: 2.11s	remaining: 1.03s
672:	learn: 0.3449861	total: 2.11s	remaining: 1.02s
673:	learn: 0.3449200	total: 2.11s	remaining: 1.02s
674:	learn: 0.3448865	total: 2.11s	remaining: 1.02s
675:	learn: 0.3448361	total: 2.12s	remaining: 1.01s
676:	learn: 0.3447756	total: 2.12s	remaining: 1.01s
677:	learn: 0.3447273	total: 2.13s	remaining: 1.01s
678:	learn: 0.3446750	total: 2.13s	remaining: 1.01s
679:	learn: 0.3446153	total: 2.14s	remaining: 1.01s
680:	learn: 0.3445610	total: 2.14s	remaining: 1s
681:	learn: 0.3445052	total: 2.15s	remaining: 1s
682:	learn: 0.3444793	total: 2.15s	remaining: 998ms
683:	learn: 0.3443867	total: 2.15s	remaining: 994ms
684:	learn: 0.3443494	total: 2.15s	remaining: 991ms
685:	learn: 0.3443020	total: 2.16s	remaining: 987ms
686:	learn: 0.3442534	total: 2.16s	remaining: 984ms
687:	learn: 0.3442268	total: 2.16s	remaining: 981ms
688:	learn: 0.3441903	total: 2.17s	remaining: 978ms

689:	learn: 0.3441250	total: 2.17s	remaining: 976ms
690:	learn: 0.3440583	total: 2.18s	remaining: 973ms
691:	learn: 0.3440064	total: 2.18s	remaining: 972ms
692:	learn: 0.3439608	total: 2.19s	remaining: 968ms
693:	learn: 0.3439209	total: 2.19s	remaining: 965ms
694:	learn: 0.3438447	total: 2.19s	remaining: 962ms
695:	learn: 0.3437938	total: 2.19s	remaining: 958ms
696:	learn: 0.3437560	total: 2.2s	remaining: 955ms
697:	learn: 0.3437060	total: 2.2s	remaining: 952ms
698:	learn: 0.3436644	total: 2.2s	remaining: 948ms
699:	learn: 0.3436018	total: 2.2s	remaining: 945ms
700:	learn: 0.3435657	total: 2.21s	remaining: 942ms
701:	learn: 0.3434859	total: 2.21s	remaining: 939ms
702:	learn: 0.3434449	total: 2.23s	remaining: 940ms
703:	learn: 0.3433978	total: 2.23s	remaining: 938ms
704:	learn: 0.3433236	total: 2.23s	remaining: 935ms
705:	learn: 0.3432817	total: 2.24s	remaining: 932ms
706:	learn: 0.3432167	total: 2.24s	remaining: 929ms
707:	learn: 0.3431723	total: 2.25s	remaining: 927ms
708:	learn: 0.3431345	total: 2.25s	remaining: 923ms
709:	learn: 0.3430819	total: 2.25s	remaining: 920ms
710:	learn: 0.3430027	total: 2.25s	remaining: 916ms
711:	learn: 0.3429522	total: 2.26s	remaining: 913ms
712:	learn: 0.3428752	total: 2.26s	remaining: 909ms
713:	learn: 0.3428335	total: 2.26s	remaining: 906ms
714:	learn: 0.3427913	total: 2.26s	remaining: 903ms
715:	learn: 0.3427069	total: 2.27s	remaining: 899ms
716:	learn: 0.3426516	total: 2.27s	remaining: 896ms
717:	learn: 0.3426178	total: 2.27s	remaining: 893ms
718:	learn: 0.3425724	total: 2.28s	remaining: 890ms
719:	learn: 0.3424933	total: 2.28s	remaining: 887ms
720:	learn: 0.3424577	total: 2.28s	remaining: 884ms
721:	learn: 0.3423982	total: 2.29s	remaining: 882ms
722:	learn: 0.3423472	total: 2.29s	remaining: 879ms
723:	learn: 0.3422817	total: 2.3s	remaining: 875ms
724:	learn: 0.3422234	total: 2.3s	remaining: 872ms
725:	learn: 0.3422027	total: 2.3s	remaining: 869ms
726:	learn: 0.3421467	total: 2.3s	remaining: 865ms
727:	learn: 0.3420853	total: 2.31s	remaining: 862ms
728:	learn: 0.3420095	total: 2.31s	remaining: 859ms
729:	learn: 0.3419604	total: 2.31s	remaining: 856ms
730:	learn: 0.3419113	total: 2.32s	remaining: 853ms
731:	learn: 0.3418123	total: 2.32s	remaining: 849ms
732:	learn: 0.3417527	total: 2.32s	remaining: 846ms
733:	learn: 0.3416952	total: 2.33s	remaining: 843ms
734:	learn: 0.3416495	total: 2.33s	remaining: 839ms
735:	learn: 0.3415924	total: 2.33s	remaining: 836ms
736:	learn: 0.3415179	total: 2.33s	remaining: 833ms
737:	learn: 0.3414806	total: 2.34s	remaining: 830ms
738:	learn: 0.3414306	total: 2.34s	remaining: 826ms
739:	learn: 0.3413586	total: 2.34s	remaining: 823ms
740:	learn: 0.3413144	total: 2.35s	remaining: 820ms
741:	learn: 0.3412853	total: 2.35s	remaining: 819ms
742:	learn: 0.3412293	total: 2.36s	remaining: 816ms
743:	learn: 0.3412069	total: 2.36s	remaining: 813ms
744:	learn: 0.3411559	total: 2.37s	remaining: 810ms
745:	learn: 0.3411000	total: 2.37s	remaining: 807ms
746:	learn: 0.3410485	total: 2.37s	remaining: 804ms
747:	learn: 0.3410226	total: 2.38s	remaining: 801ms
748:	learn: 0.3409763	total: 2.38s	remaining: 799ms
749:	learn: 0.3409253	total: 2.39s	remaining: 797ms
750:	learn: 0.3408696	total: 2.39s	remaining: 794ms
751:	learn: 0.3408159	total: 2.4s	remaining: 791ms
752:	learn: 0.3407731	total: 2.4s	remaining: 788ms
753:	learn: 0.3407267	total: 2.41s	remaining: 785ms
754:	learn: 0.3406561	total: 2.41s	remaining: 782ms
755:	learn: 0.3406140	total: 2.41s	remaining: 779ms
756:	learn: 0.3405701	total: 2.42s	remaining: 776ms
757:	learn: 0.3405152	total: 2.42s	remaining: 772ms
758:	learn: 0.3404670	total: 2.42s	remaining: 769ms
759:	learn: 0.3403885	total: 2.42s	remaining: 765ms
760:	learn: 0.3403194	total: 2.43s	remaining: 762ms
761:	learn: 0.3402761	total: 2.43s	remaining: 759ms
762:	learn: 0.3402453	total: 2.43s	remaining: 756ms
763:	learn: 0.3402023	total: 2.44s	remaining: 753ms
764:	learn: 0.3401712	total: 2.44s	remaining: 750ms
765:	learn: 0.3401373	total: 2.44s	remaining: 747ms
766:	learn: 0.3400974	total: 2.45s	remaining: 744ms
767:	learn: 0.3400531	total: 2.45s	remaining: 741ms
768:	learn: 0.3400182	total: 2.46s	remaining: 738ms
769:	learn: 0.3399826	total: 2.46s	remaining: 735ms
770:	learn: 0.3399284	total: 2.46s	remaining: 732ms
771:	learn: 0.3398939	total: 2.47s	remaining: 729ms
772:	learn: 0.3398453	total: 2.47s	remaining: 726ms
773:	learn: 0.3397673	total: 2.48s	remaining: 723ms
774:	learn: 0.3397293	total: 2.48s	remaining: 720ms
775:	learn: 0.3396768	total: 2.48s	remaining: 717ms
776:	learn: 0.3396304	total: 2.48s	remaining: 713ms
777:	learn: 0.3395576	total: 2.49s	remaining: 711ms
778:	learn: 0.3394843	total: 2.49s	remaining: 708ms
779:	learn: 0.3394399	total: 2.5s	remaining: 705ms
780:	learn: 0.3393883	total: 2.5s	remaining: 702ms
781:	learn: 0.3393398	total: 2.51s	remaining: 700ms
782:	learn: 0.3392695	total: 2.51s	remaining: 696ms
783:	learn: 0.3392269	total: 2.52s	remaining: 693ms
784:	learn: 0.3391852	total: 2.52s	remaining: 690ms
785:	learn: 0.3390953	total: 2.52s	remaining: 687ms
786:	learn: 0.3390345	total: 2.53s	remaining: 684ms
787:	learn: 0.3389927	total: 2.53s	remaining: 681ms
788:	learn: 0.3389199	total: 2.54s	remaining: 678ms
789:	learn: 0.3388639	total: 2.54s	remaining: 677ms
790:	learn: 0.3388144	total: 2.55s	remaining: 673ms
791:	learn: 0.3387550	total: 2.55s	remaining: 670ms
792:	learn: 0.3387121	total: 2.55s	remaining: 666ms
793:	learn: 0.3386471	total: 2.56s	remaining: 663ms
794:	learn: 0.3385729	total: 2.56s	remaining: 660ms
795:	learn: 0.3385393	total: 2.56s	remaining: 656ms
796:	learn: 0.3384954	total: 2.56s	remaining: 653ms
797:	learn: 0.3384168	total: 2.56s	remaining: 649ms
798:	learn: 0.3383496	total: 2.57s	remaining: 646ms
799:	learn: 0.3382855	total: 2.57s	remaining: 643ms
800:	learn: 0.3382406	total: 2.57s	remaining: 640ms
801:	learn: 0.3382024	total: 2.58s	remaining: 636ms
802:	learn: 0.3381494	total: 2.58s	remaining: 633ms
803:	learn: 0.3380721	total: 2.58s	remaining: 629ms
804:	learn: 0.3380436	total: 2.58s	remaining: 626ms
805:	learn: 0.3379932	total: 2.59s	remaining: 623ms
806:	learn: 0.3379598	total: 2.59s	remaining: 620ms
807:	learn: 0.3379306	total: 2.59s	remaining: 617ms
808:	learn: 0.3378762	total: 2.6s	remaining: 613ms
809:	learn: 0.3377908	total: 2.6s	remaining: 610ms
810:	learn: 0.3377289	total: 2.6s	remaining: 606ms
811:	learn: 0.3376833	total: 2.6s	remaining: 603ms
812:	learn: 0.3376109	total: 2.61s	remaining: 600ms
813:	learn: 0.3375698	total: 2.61s	remaining: 596ms
814:	learn: 0.3375182	total: 2.61s	remaining: 593ms
815:	learn: 0.3374569	total: 2.61s	remaining: 589ms
816:	learn: 0.3374036	total: 2.62s	remaining: 586ms
817:	learn: 0.3373507	total: 2.62s	remaining: 583ms
818:	learn: 0.3372915	total: 2.62s	remaining: 579ms
819:	learn: 0.3372367	total: 2.62s	remaining: 576ms
820:	learn: 0.3371811	total: 2.63s	remaining: 573ms
821:	learn: 0.3371244	total: 2.63s	remaining: 569ms
822:	learn: 0.3370681	total: 2.63s	remaining: 566ms
823:	learn: 0.3370161	total: 2.63s	remaining: 563ms
824:	learn: 0.3369740	total: 2.64s	remaining: 561ms
825:	learn: 0.3369263	total: 2.65s	remaining: 558ms
826:	learn: 0.3368710	total: 2.65s	remaining: 554ms
827:	learn: 0.3368334	total: 2.65s	remaining: 551ms
828:	learn: 0.3367928	total: 2.65s	remaining: 548ms
829:	learn: 0.3367345	total: 2.66s	remaining: 544ms
830:	learn: 0.3366892	total: 2.66s	remaining: 541ms
831:	learn: 0.3366405	total: 2.66s	remaining: 538ms
832:	learn: 0.3365751	total: 2.66s	remaining: 534ms
833:	learn: 0.3365253	total: 2.67s	remaining: 531ms
834:	learn: 0.3364506	total: 2.67s	remaining: 528ms
835:	learn: 0.3363908	total: 2.67s	remaining: 525ms
836:	learn: 0.3363461	total: 2.68s	remaining: 521ms
837:	learn: 0.3362838	total: 2.68s	remaining: 518ms
838:	learn: 0.3362519	total: 2.68s	remaining: 515ms
839:	learn: 0.3361692	total: 2.68s	remaining: 511ms
840:	learn: 0.3361171	total: 2.69s	remaining: 508ms
841:	learn: 0.3360714	total: 2.69s	remaining: 505ms
842:	learn: 0.3360264	total: 2.69s	remaining: 501ms
843:	learn: 0.3359734	total: 2.7s	remaining: 499ms
844:	learn: 0.3359058	total: 2.7s	remaining: 495ms
845:	learn: 0.3358506	total: 2.7s	remaining: 492ms
846:	learn: 0.3358142	total: 2.71s	remaining: 489ms
847:	learn: 0.3357700	total: 2.71s	remaining: 486ms
848:	learn: 0.3357351	total: 2.71s	remaining: 483ms
849:	learn: 0.3356863	total: 2.72s	remaining: 480ms
850:	learn: 0.3356256	total: 2.72s	remaining: 476ms
851:	learn: 0.3355879	total: 2.72s	remaining: 473ms
852:	learn: 0.3355415	total: 2.73s	remaining: 470ms
853:	learn: 0.3354939	total: 2.73s	remaining: 466ms
854:	learn: 0.3354353	total: 2.73s	remaining: 463ms
855:	learn: 0.3353970	total: 2.73s	remaining: 460ms
856:	learn: 0.3353601	total: 2.73s	remaining: 456ms
857:	learn: 0.3352867	total: 2.74s	remaining: 453ms
858:	learn: 0.3352410	total: 2.74s	remaining: 450ms
859:	learn: 0.3352010	total: 2.74s	remaining: 446ms
860:	learn: 0.3351649	total: 2.74s	remaining: 443ms
861:	learn: 0.3351035	total: 2.75s	remaining: 440ms
862:	learn: 0.3350630	total: 2.75s	remaining: 437ms
863:	learn: 0.3350187	total: 2.75s	remaining: 433ms
864:	learn: 0.3349770	total: 2.75s	remaining: 430ms
865:	learn: 0.3349366	total: 2.76s	remaining: 427ms
866:	learn: 0.3348574	total: 2.76s	remaining: 423ms
867:	learn: 0.3347962	total: 2.76s	remaining: 420ms
868:	learn: 0.3347614	total: 2.77s	remaining: 417ms
869:	learn: 0.3347159	total: 2.77s	remaining: 414ms
870:	learn: 0.3346662	total: 2.77s	remaining: 411ms
871:	learn: 0.3346090	total: 2.77s	remaining: 407ms
872:	learn: 0.3345693	total: 2.78s	remaining: 404ms
873:	learn: 0.3345301	total: 2.78s	remaining: 401ms
874:	learn: 0.3344763	total: 2.78s	remaining: 398ms
875:	learn: 0.3344254	total: 2.79s	remaining: 394ms
876:	learn: 0.3343796	total: 2.79s	remaining: 391ms
877:	learn: 0.3343252	total: 2.79s	remaining: 388ms
878:	learn: 0.3342762	total: 2.79s	remaining: 385ms
879:	learn: 0.3342289	total: 2.8s	remaining: 381ms
880:	learn: 0.3341719	total: 2.8s	remaining: 378ms
881:	learn: 0.3341148	total: 2.8s	remaining: 375ms
882:	learn: 0.3340673	total: 2.8s	remaining: 371ms
883:	learn: 0.3339955	total: 2.81s	remaining: 368ms
884:	learn: 0.3339444	total: 2.81s	remaining: 365ms
885:	learn: 0.3338805	total: 2.81s	remaining: 362ms
886:	learn: 0.3338355	total: 2.81s	remaining: 359ms
887:	learn: 0.3337886	total: 2.82s	remaining: 355ms
888:	learn: 0.3337442	total: 2.82s	remaining: 352ms
889:	learn: 0.3337019	total: 2.82s	remaining: 349ms
890:	learn: 0.3336582	total: 2.83s	remaining: 346ms
891:	learn: 0.3336013	total: 2.83s	remaining: 342ms
892:	learn: 0.3335323	total: 2.83s	remaining: 339ms
893:	learn: 0.3334807	total: 2.83s	remaining: 336ms
894:	learn: 0.3334480	total: 2.84s	remaining: 333ms

895:	learn: 0.3333998	total: 2.84s	remaining: 330ms
896:	learn: 0.3333589	total: 2.84s	remaining: 326ms
897:	learn: 0.3333104	total: 2.85s	remaining: 323ms
898:	learn: 0.3332677	total: 2.85s	remaining: 320ms
899:	learn: 0.3332061	total: 2.85s	remaining: 317ms
900:	learn: 0.3331375	total: 2.85s	remaining: 314ms
901:	learn: 0.3330979	total: 2.86s	remaining: 310ms
902:	learn: 0.3330446	total: 2.86s	remaining: 307ms
903:	learn: 0.3330009	total: 2.86s	remaining: 304ms
904:	learn: 0.3329484	total: 2.86s	remaining: 301ms
905:	learn: 0.3328740	total: 2.87s	remaining: 298ms
906:	learn: 0.3328271	total: 2.87s	remaining: 294ms
907:	learn: 0.3327741	total: 2.87s	remaining: 291ms
908:	learn: 0.3327291	total: 2.88s	remaining: 288ms
909:	learn: 0.3326687	total: 2.88s	remaining: 285ms
910:	learn: 0.3326301	total: 2.88s	remaining: 281ms
911:	learn: 0.3325648	total: 2.88s	remaining: 278ms
912:	learn: 0.3325267	total: 2.89s	remaining: 275ms
913:	learn: 0.3324930	total: 2.89s	remaining: 272ms
914:	learn: 0.3324171	total: 2.89s	remaining: 269ms
915:	learn: 0.3323641	total: 2.9s	remaining: 265ms
916:	learn: 0.3323059	total: 2.9s	remaining: 262ms
917:	learn: 0.3322561	total: 2.9s	remaining: 259ms
918:	learn: 0.3322246	total: 2.9s	remaining: 256ms
919:	learn: 0.3321869	total: 2.91s	remaining: 253ms
920:	learn: 0.3321379	total: 2.91s	remaining: 250ms
921:	learn: 0.3320918	total: 2.91s	remaining: 246ms
922:	learn: 0.3320405	total: 2.91s	remaining: 243ms
923:	learn: 0.3319869	total: 2.92s	remaining: 240ms
924:	learn: 0.3319564	total: 2.92s	remaining: 237ms
925:	learn: 0.3319197	total: 2.92s	remaining: 233ms
926:	learn: 0.3318610	total: 2.92s	remaining: 230ms
927:	learn: 0.3318156	total: 2.93s	remaining: 227ms
928:	learn: 0.3317757	total: 2.93s	remaining: 224ms
929:	learn: 0.3317444	total: 2.93s	remaining: 221ms
930:	learn: 0.3316995	total: 2.93s	remaining: 217ms
931:	learn: 0.3316461	total: 2.94s	remaining: 214ms
932:	learn: 0.3316120	total: 2.94s	remaining: 211ms
933:	learn: 0.3315714	total: 2.94s	remaining: 208ms
934:	learn: 0.3315161	total: 2.94s	remaining: 205ms
935:	learn: 0.3314668	total: 2.94s	remaining: 201ms
936:	learn: 0.3314259	total: 2.95s	remaining: 198ms
937:	learn: 0.3313756	total: 2.95s	remaining: 195ms
938:	learn: 0.3313381	total: 2.95s	remaining: 192ms
939:	learn: 0.3312967	total: 2.96s	remaining: 189ms
940:	learn: 0.3312574	total: 2.96s	remaining: 186ms
941:	learn: 0.3312134	total: 2.96s	remaining: 182ms
942:	learn: 0.3311734	total: 2.96s	remaining: 179ms
943:	learn: 0.3311400	total: 2.96s	remaining: 176ms
944:	learn: 0.3311127	total: 2.97s	remaining: 173ms
945:	learn: 0.3310709	total: 2.97s	remaining: 170ms
946:	learn: 0.3310126	total: 2.97s	remaining: 166ms
947:	learn: 0.3309797	total: 2.98s	remaining: 163ms
948:	learn: 0.3309257	total: 2.98s	remaining: 160ms
949:	learn: 0.3308820	total: 2.98s	remaining: 157ms
950:	learn: 0.3308453	total: 2.98s	remaining: 154ms
951:	learn: 0.3308017	total: 2.98s	remaining: 150ms
952:	learn: 0.3307563	total: 2.99s	remaining: 147ms
953:	learn: 0.3307091	total: 2.99s	remaining: 144ms
954:	learn: 0.3306684	total: 2.99s	remaining: 141ms
955:	learn: 0.3306234	total: 3s	remaining: 138ms
956:	learn: 0.3305834	total: 3s	remaining: 135ms
957:	learn: 0.3305520	total: 3s	remaining: 132ms
958:	learn: 0.3305110	total: 3s	remaining: 128ms
959:	learn: 0.3304471	total: 3.01s	remaining: 125ms
960:	learn: 0.3303986	total: 3.01s	remaining: 122ms
961:	learn: 0.3303523	total: 3.01s	remaining: 119ms
962:	learn: 0.3303138	total: 3.02s	remaining: 116ms
963:	learn: 0.3302613	total: 3.02s	remaining: 113ms
964:	learn: 0.3302247	total: 3.02s	remaining: 110ms
965:	learn: 0.3301903	total: 3.02s	remaining: 106ms
966:	learn: 0.3301448	total: 3.03s	remaining: 103ms
967:	learn: 0.3301074	total: 3.03s	remaining: 100ms
968:	learn: 0.3300541	total: 3.03s	remaining: 97ms
969:	learn: 0.3300102	total: 3.04s	remaining: 93.9ms
970:	learn: 0.3299623	total: 3.04s	remaining: 90.7ms
971:	learn: 0.3299209	total: 3.04s	remaining: 87.6ms
972:	learn: 0.3298876	total: 3.04s	remaining: 84.5ms
973:	learn: 0.3298399	total: 3.05s	remaining: 81.4ms
974:	learn: 0.3297929	total: 3.05s	remaining: 78.3ms
975:	learn: 0.3297597	total: 3.06s	remaining: 75.1ms
976:	learn: 0.3297214	total: 3.06s	remaining: 72ms
977:	learn: 0.3296854	total: 3.06s	remaining: 68.9ms
978:	learn: 0.3296308	total: 3.06s	remaining: 65.7ms
979:	learn: 0.3296007	total: 3.07s	remaining: 62.6ms
980:	learn: 0.3295565	total: 3.07s	remaining: 59.4ms
981:	learn: 0.3294858	total: 3.07s	remaining: 56.3ms
982:	learn: 0.3294489	total: 3.07s	remaining: 53.2ms
983:	learn: 0.3294165	total: 3.08s	remaining: 50ms
984:	learn: 0.3293754	total: 3.08s	remaining: 46.9ms
985:	learn: 0.3293320	total: 3.08s	remaining: 43.8ms
986:	learn: 0.3292594	total: 3.08s	remaining: 40.6ms
987:	learn: 0.3292279	total: 3.09s	remaining: 37.5ms
988:	learn: 0.3291881	total: 3.09s	remaining: 34.4ms
989:	learn: 0.3291462	total: 3.09s	remaining: 31.2ms
990:	learn: 0.3291077	total: 3.1s	remaining: 28.1ms
991:	learn: 0.3290604	total: 3.1s	remaining: 25ms
992:	learn: 0.3290068	total: 3.1s	remaining: 21.9ms
993:	learn: 0.3289723	total: 3.1s	remaining: 18.7ms
994:	learn: 0.3289263	total: 3.11s	remaining: 15.6ms
995:	learn: 0.3288550	total: 3.11s	remaining: 12.5ms
996:	learn: 0.3288085	total: 3.11s	remaining: 9.36ms
997:	learn: 0.3287771	total: 3.11s	remaining: 6.24ms
998:	learn: 0.3287343	total: 3.12s	remaining: 3.12ms
999:	learn: 0.3286862	total: 3.12s	remaining: 0us

In [247]:
#Limpieza del dataset de test

oportunidades = pd.read_csv("Test_TP2_Datos_2020-2C.csv")
oportunidades['Account_Created_Date'] = pd.to_datetime(oportunidades['Account_Created_Date'])
oportunidades['Opportunity_Created_Date'] = pd.to_datetime(oportunidades['Opportunity_Created_Date'])
oportunidades['Quote_Expiry_Date'] = pd.to_datetime(oportunidades['Quote_Expiry_Date'])
oportunidades['Last_Modified_Date'] = pd.to_datetime(oportunidades['Last_Modified_Date'])
oportunidades['Planned_Delivery_Start_Date'] = pd.to_datetime(oportunidades['Planned_Delivery_Start_Date'])
oportunidades['Planned_Delivery_End_Date'] = pd.to_datetime(oportunidades['Planned_Delivery_End_Date'])
oportunidades_japon = (oportunidades.loc[oportunidades['Region'] == 'Japan'])
oportunidades = (oportunidades.loc[oportunidades['Region'] != 'Japan'])
#oportunidades_japon = oportunidades_japon.iloc[:,:3]
oportunidades_japon['Territory'] = oportunidades_japon['Territory'].replace({'None':'Japan'})
oportunidades = pd.concat([oportunidades, oportunidades_japon], axis=0)
oportunidades['Region'] = oportunidades['Region'].replace({'Japan':'APAC', 'Middle East':'EMEA'})
oportunidades[oportunidades.select_dtypes(['object']).columns] = oportunidades.select_dtypes(['object']).apply(lambda x: x.astype('category'))
#oportunidades = oportunidades.loc[oportunidades['Territory'] != 'None']
#oportunidades = oportunidades.dropna()

filtro_terminos_entrega = oportunidades['Pricing, Delivery_Terms_Quote_Appr']\
     == oportunidades['Pricing, Delivery_Terms_Approved']

filtro_codigo_burocratico = oportunidades['Bureaucratic_Code_0_Approval']\
     == oportunidades['Bureaucratic_Code_0_Approved']

oportunidades = oportunidades.drop(['Pricing, Delivery_Terms_Quote_Appr'\
    ,'Pricing, Delivery_Terms_Approved', 'Bureaucratic_Code_0_Approval'\
        , 'Bureaucratic_Code_0_Approved', 'Submitted_for_Approval'], axis = 'columns')

oportunidades["Moneda_Convertida"] = (oportunidades['ASP'] / oportunidades['ASP_(converted)'])
oportunidades_posibles = (filtro_terminos_entrega & filtro_codigo_burocratico)

oportunidades.insert(3,'Es_Oportunidad_Posible', oportunidades_posibles)

oportunidades['Es_Oportunidad_Posible'] = oportunidades['Es_Oportunidad_Posible'].replace(
    {True:1, False:0})

oportunidades

,ID,Region,Territory,Es_Oportunidad_Posible,Bureaucratic_Code,Account_Created_Date,Source,Billing_Country,Account_Name,Opportunity_Name,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Prod_Category_A,Moneda_Convertida
0,6140,EMEA,Germany,1,Bureaucratic_Code_4,2017-07-05,Source_7,Germany,Account_Name_978,Opportunity_Name_6118,...,Q2,2019,NaT,0,EUR,162240.0,EUR,367419.0,Prod_Category_A_None,0.884089
1,6146,EMEA,Germany,1,Bureaucratic_Code_4,2017-07-05,Source_7,Germany,Account_Name_978,Opportunity_Name_6118,...,Q2,2019,NaT,0,EUR,78624.0,EUR,367419.0,Prod_Category_A_None,0.884100
2,6151,EMEA,Germany,1,Bureaucratic_Code_4,2017-07-05,Source_7,Germany,Account_Name_978,Opportunity_Name_6118,...,Q2,2019,NaT,0,EUR,126555.0,EUR,367419.0,Prod_Category_A_None,0.884102
3,6118,EMEA,Germany,1,Bureaucratic_Code_4,2017-07-05,Source_7,Germany,Account_Name_978,Opportunity_Name_6117,...,Q2,2019,NaT,1,EUR,243360.0,EUR,757783.5,Prod_Category_A_None,0.884089
4,6124,EMEA,Germany,1,Bureaucratic_Code_4,2017-07-05,Source_7,Germany,Account_Name_978,Opportunity_Name_6117,...,Q2,2019,NaT,0,EUR,157248.0,EUR,757783.5,Prod_Category_A_None,0.884100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,15649,APAC,Japan,1,Bureaucratic_Code_4,2016-12-09,None,Japan,Account_Name_1039,Opportunity_Name_2761,...,Q2,2019,NaT,0,JPY,30000.0,JPY,73200.0,Prod_Category_A_None,NaN
2513,15655,APAC,Japan,1,Bureaucratic_Code_4,2016-12-09,None,Japan,Account_Name_1039,Opportunity_Name_2761,...,Q2,2019,NaT,0,JPY,43200.0,JPY,73200.0,Prod_Category_A_None,111.228519
2537,18605,APAC,Japan,1,Bureaucratic_Code_4,2013-07-28,Source_3,Japan,Account_Name_1075,Opportunity_Name_6475,...,Q3,2020,NaT,12,USD,4079928.6,USD,4079928.6,Prod_Category_A_None,1.000000
2542,5817,APAC,Japan,1,Bureaucratic_Code_4,2017-06-30,None,Japan,Account_Name_1542,Opportunity_Name_7265,...,Q3,2019,NaT,0,JPY,5068800.0,JPY,5068800.0,Prod_Category_A_None,111.229081
2543,11318,APAC,Japan,1,Bureaucratic_Code_4,2019-02-12,None,Japan,Account_Name_1377,Opportunity_Name_11565,...,Q4,2019,NaT,1,JPY,20282500.0,JPY,20282500.0,Prod_Category_A_None,111.231449

In [248]:
#Encoding para el dataset de testeo, con los mismos que en training set.

encoding_owners = oportunidades.groupby('Opportunity_Owner').agg({'Total_Amount':'mean'})
encoding_owners.columns = ['Encoding_Vendedor']
encoding_owners = encoding_owners.reset_index()
oportunidades = oportunidades.merge(encoding_owners, how='inner', on='Opportunity_Owner')

encoding_territory = oportunidades.groupby('Territory').agg({'Total_Amount' : 'mean'})
encoding_territory.columns = ['Encoding_Territorio']
encoding_territory = encoding_territory.reset_index()
oportunidades = oportunidades.merge(encoding_territory, how='inner', on='Territory')

encoding_region = oportunidades.groupby('Region').agg({'Total_Amount' : 'mean'})
encoding_region.columns = ['Encoding_Region']
encoding_region = encoding_region.reset_index()
oportunidades = oportunidades.merge(encoding_region, how='inner', on='Region')

encoding_moneda = oportunidades.groupby('Total_Amount_Currency').agg({'Moneda_Convertida' : 'mean'})
encoding_moneda.columns = ['Encoding_Moneda']
encoding_moneda = encoding_moneda.reset_index()
oportunidades = oportunidades.merge(encoding_moneda, how='inner', on='Total_Amount_Currency')
oportunidades

oportunidades = pd.concat([oportunidades, pd.get_dummies(oportunidades['Bureaucratic_Code'])],axis='columns')

encoding_bill_c = oportunidades.groupby('Billing_Country').agg({'Total_Amount' : 'mean'})
encoding_bill_c.columns = ['Encoding_Billing_Country']
encoding_bill_c = encoding_bill_c.reset_index()
oportunidades = oportunidades.merge(encoding_bill_c, how='inner', on='Billing_Country')
oportunidades

oportunidades = pd.concat([oportunidades, pd.get_dummies(oportunidades['Account_Type'])],axis='columns')

oportunidades = pd.concat([oportunidades,pd.get_dummies(oportunidades['Delivery_Terms'])],axis='columns')

encoding_product_family = oportunidades.groupby('Product_Family').agg({'Total_Amount' : 'mean'})
encoding_product_family.columns = ['Encoding_Prod_Family']
encoding_product_family = encoding_product_family.reset_index()
oportunidades = oportunidades.merge(encoding_product_family, how='inner', on='Product_Family')

oportunidades['Opportunity_Created_Year'] = oportunidades['Opportunity_Created_Date'].dt.year
oportunidades['Opportunity_Created_Month'] = oportunidades['Opportunity_Created_Date'].dt.month
oportunidades['Año_Por_Mes'] = oportunidades['Opportunity_Created_Year'] * oportunidades['Opportunity_Created_Month']
oportunidades

,ID,Region,Territory,Es_Oportunidad_Posible,Bureaucratic_Code,Account_Created_Date,Source,Billing_Country,Account_Name,Opportunity_Name,...,Delivery_Terms_3,Delivery_Terms_4,Delivery_Terms_5,Delivery_Terms_6,Delivery_Terms_7,Delivery_Terms_8,Encoding_Prod_Family,Opportunity_Created_Year,Opportunity_Created_Month,Año_Por_Mes
0,6140,EMEA,Germany,1,Bureaucratic_Code_4,2017-07-05,Source_7,Germany,Account_Name_978,Opportunity_Name_6118,...,0,0,0,0,0,0,1.347805e+07,2019,4,8076
1,6118,EMEA,Germany,1,Bureaucratic_Code_4,2017-07-05,Source_7,Germany,Account_Name_978,Opportunity_Name_6117,...,0,0,0,0,0,0,1.347805e+07,2019,4,8076
2,18450,EMEA,Germany,1,Bureaucratic_Code_4,2013-07-27,Source_9,Germany,Account_Name_533,Opportunity_Name_3499,...,0,0,0,0,0,0,1.347805e+07,2019,1,2019
3,18307,EMEA,Germany,0,Bureaucratic_Code_5,2013-07-27,Source_9,Germany,Account_Name_533,Opportunity_Name_4292,...,0,0,0,0,0,0,1.347805e+07,2019,2,4038
4,14441,EMEA,Germany,1,Bureaucratic_Code_4,2013-07-27,Source_7,Germany,Account_Name_263,Opportunity_Name_2981,...,0,0,0,0,0,0,1.347805e+07,2019,3,6057
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2546,11918,APAC,Japan,1,Bureaucratic_Code_4,2019-03-11,None,Japan,Account_Name_1533,Opportunity_Name_9046,...,0,0,0,1,0,0,3.300000e+05,2019,3,6057
2547,11379,APAC,Japan,0,Bureaucratic_Code_5,2019-02-12,None,Japan,Account_Name_1377,Opportunity_Name_12892,...,0,1,0,0,0,0,1.351350e+08,2019,4,8076
2548,6071,APAC,Japan,1,Bureaucratic_Code_4,2015-12-21,None,Japan,Account_Name_1508,Opportunity_Name_278,...,0,1,0,0,0,0,1.800000e+04,2019,2,4038
2549,9305,APAC,Japan,1,Bureaucratic_Code_4,2016-08-17,None,Japan,Account_Name_1240,Opportunity_Name_313,...,0,1,0,0,0,0,1.800000e+04,2019,3,6057
2550,6803,APAC,Japan,1,Bureaucratic_Code_4,2015-12-21,None,Japan,Account_Name_1508,Opportunity_Name_312,...,0,1,0,0,0,0,1.800000e+04,2019,3,6057

In [249]:
#Hacemos el groupby

# std_deviation_amounts = oportunidades.groupby('Opportunity_ID').agg({'TRF':'std'})
# std_deviation_amounts.columns = ['TRF_Std']
# std_deviation_amounts = std_deviation_amounts.reset_index()
x_test = oportunidades.groupby('Opportunity_ID').agg({'Año_Por_Mes' : 'mean',\
                                                       'TRF': 'mean',\
                                                      'Encoding_Moneda':'mean', 'Total_Amount': 'sum',\
                                                      'Total_Taxable_Amount':'mean', 'Encoding_Region':'mean',\
                                                      'Encoding_Territorio':'mean','Encoding_Vendedor':'mean',\
                                                      'Es_Oportunidad_Posible':'mean',\
                                                       'Encoding_Billing_Country':'mean',\
                                                      'Encoding_Prod_Family':'mean'
                                                      })
x_test = x_test.reset_index()
#x_test = x_test.merge(std_deviation_amounts, on='Opportunity_ID', how='inner')
x_test = x_test.set_index('Opportunity_ID')
#x_test['Total_Amount_Std'] = x_test['Total_Amount_Std'].replace({np.nan:0})
#x_test['Total_Tax_Amount_Std'] = x_test['Total_Tax_Amount_Std'].replace({np.nan:0})
x_test['Total_Amount'] = (x_test['Total_Amount'] / x_test['Encoding_Moneda']) 
x_test['Total_Taxable_Amount'] = (x_test['Total_Taxable_Amount'] / x_test['Encoding_Moneda']) 
x_test['Diferencia_Amounts'] = (x_test['Total_Amount'] - x_test['Total_Taxable_Amount'])
x_test = x_test.drop(['Encoding_Moneda'], axis='columns')
#x_test['TRF_Std'] = x_test['TRF_Std'].replace({np.nan:0})
x_test

SpecificationError: Column(s) ['Stage'] do not exist

In [ ]:
x_test = x_test.select_dtypes(exclude=['datetime', 'category'])
predictions = xg_reg.predict(x_test)
predictions2 = xg_reg2.predict(x_test)
predictions3 = cat_reg.predict(x_test)
predictions_final = (predictions+predictions2+predictions3)/3
predictions_final

In [ ]:
predictions

In [ ]:
predictions2

In [ ]:
predictions3

In [ ]:
x_test = x_test.reset_index()
serie1 = pd.DataFrame(x_test['Opportunity_ID'])
serie2 = pd.DataFrame(predictions_final)
df = pd.DataFrame(serie1)
df['Target'] = serie2
df.columns = ['Opportunity_ID', 'Target']
df

In [ ]:
df.to_csv("Predicciones.csv", index=False)

In [ ]:
division_x_train, division_x_test, division_y_train, division_y_test = train_test_split(x_train, y_train, test_size = 0.3,\
                                                                                       random_state = 5555)

xg_reg.fit(division_x_train, division_y_train)
xg_reg2.fit(division_x_train, division_y_train)
cat_reg.fit(division_x_train, division_y_train)

In [ ]:
accuracy1 = accuracy_score(division_y_test, xg_reg.predict(division_x_test).round())
log_loss1 = log_loss(division_y_test, xg_reg.predict(division_x_test))

accuracy2 = accuracy_score(division_y_test, xg_reg2.predict(division_x_test).round())
log_loss2 = log_loss(division_y_test, xg_reg2.predict(division_x_test))

accuracy3 = accuracy_score(division_y_test, cat_reg.predict(division_x_test).round())
log_loss3 = log_loss(division_y_test, cat_reg.predict(division_x_test))

promedio = (xg_reg.predict(division_x_test)+xg_reg2.predict(division_x_test)+cat_reg.predict(division_x_test)) / 3

accuracy4 = accuracy_score(division_y_test, promedio.round())
log_loss4 = log_loss(division_y_test, promedio)

In [ ]:
print("Accuracy1 = " + str(accuracy1) + " ; LogLoss1 = " + str(log_loss1) \
      + "\nAccuracy2 = " + str(accuracy2) + " ; LogLoss2 = " + str(log_loss2)\
     + "\nAccuracy3 = " + str(accuracy3) + " ; LogLoss3 = " + str(log_loss3)
     + "\nAccuracy4 = " + str(accuracy4) + " ; LogLoss4 = " + str(log_loss4))

In [ ]:
plt.rcParams['figure.figsize'] = [12, 7]
xgb.plot_importance(xg_reg)